<script lang="ts">
  import { page } from '$app/state'; import { getPipelineDefinition, getPipelineDesign, listConnectors, pipelineErrorMessage, savePipelineDesign, validatePipelineDesign, type ConnectorDefinition, type NexetlError, type PipelineDefinition, type PipelineDesign, type PipelineDesignNodeType, type PipelineDesignValidationResult } from '$lib/api/pipelines'; import Button from '$lib/components/ui/Button.svelte'; import Alert from '$lib/components/ui/Alert.svelte';
  let pipeline = $state<PipelineDefinition | null>(null), design = $state<PipelineDesign | null>(null), connectors = $state<ConnectorDefinition[]>([]), selected = $state<string | null>(null), sourceId = $state(''), targetId = $state(''), loading = $state(true), saving = $state(false), dirty = $state(false), error = $state(''), conflict = $state(false), validation = $state<PipelineDesignValidationResult | null>(null);
  $effect(() => { const id = page.params.pipelineDefinitionId; if (id) void load(id); });
  async function load(id: string) { loading = true; try { const [p,d,c] = await Promise.all([getPipelineDefinition(id), getPipelineDesign(id), listConnectors()]); pipeline=p; design=d; connectors=c.items.filter((item) => item.availability === 'AVAILABLE'); dirty=false; } catch (failure) { error = pipelineErrorMessage(failure as NexetlError); } finally { loading=false; } }
  function add(type: PipelineDesignNodeType) { if (!design || pipeline?.state === 'ARCHIVED') return; const connector = type === 'TRANSFORM' ? null : connectors[0]?.key ?? null; design = {...design, nodes:[...design.nodes,{id:crypto.randomUUID(),type,label:type === 'TRANSFORM' ? 'Transform' : `${connectors.find((c)=>c.key===connector)?.displayName ?? type} ${type}`,connectorKey:connector,positionX:80+design.nodes.length*30,positionY:80+design.nodes.length*30}]}; dirty=true; }
  function removeNode() { if (!design || !selected || pipeline?.state === 'ARCHIVED') return; design={...design,nodes:design.nodes.filter((n)=>n.id!==selected),edges:design.edges.filter((e)=>e.sourceNodeId!==selected&&e.targetNodeId!==selected)}; selected=null; dirty=true; }
  function connect() { if (!design || pipeline?.state === 'ARCHIVED' || !sourceId || !targetId) return; design={...design,edges:[...design.edges,{id:crypto.randomUUID(),sourceNodeId:sourceId,targetNodeId:targetId}]}; dirty=true; }
  function deleteEdge(id: string) { if (!design || pipeline?.state === 'ARCHIVED') return; design={...design,edges:design.edges.filter((edge)=>edge.id!==id)}; dirty=true; }
  async function save() { if (!design) return; saving=true; error=''; conflict=false; try { design=await savePipelineDesign(design.pipelineId,design); dirty=false; } catch(failure){ const typed=failure as NexetlError; conflict=typed.code === 'NEXETL_PIPELINE_DESIGN_REVISION_CONFLICT'; error=conflict ? 'A newer version of this Pipeline Design exists.' : pipelineErrorMessage(typed); } finally { saving=false; } }
  async function validate() { if (!design) return; try { validation=await validatePipelineDesign(design.pipelineId); } catch(failure){ error=pipelineErrorMessage(failure as NexetlError); } }
  function updateLabel(event: Event) { if (!design||!selected) return; const value=(event.currentTarget as HTMLInputElement).value; design={...design,nodes:design.nodes.map((n)=>n.id===selected?{...n,label:value}:n)}; dirty=true; }
</script>
<svelte:head><title>{pipeline?.name ?? 'Pipeline'} Design | NEXETL</title></svelte:head>
{#if loading}<p>Loading Pipeline Designer…</p>{:else if error && !design}<Alert variant="error">{error}</Alert>{:else if design}<header><div><h1>{pipeline?.name}</h1><span>{pipeline?.state === 'ARCHIVED' ? 'Archived — read only' : dirty ? 'Unsaved changes' : 'Saved'} · Revision {design.revision}</span></div><div><Button variant="secondary" onclick={validate}>Validate</Button>{#if pipeline?.state !== 'ARCHIVED'}<Button loading={saving} onclick={save}>Save</Button>{/if}</div></header>{#if error}<Alert variant="error">{error}</Alert>{#if conflict}<Button variant="secondary" onclick={() => load(design!.pipelineId)}>Reload latest</Button>{/if}{/if}{#if validation}<Alert variant={validation.valid ? 'success' : 'warning'}>{validation.valid ? 'Design is structurally complete.' : validation.issues.map((issue)=>issue.message).join(' ')}</Alert>{/if}<div class="designer"><aside><h2>Node palette</h2>{#each ['SOURCE','TRANSFORM','TARGET'] as type}<Button variant="secondary" disabled={pipeline?.state === 'ARCHIVED'} onclick={() => add(type as PipelineDesignNodeType)}>Add {type.toLowerCase()}</Button>{/each}<h2>Connection</h2><label>Source<select bind:value={sourceId} disabled={pipeline?.state === 'ARCHIVED'}>{#each design.nodes as node}<option value={node.id}>{node.label}</option>{/each}</select></label><label>Target<select bind:value={targetId} disabled={pipeline?.state === 'ARCHIVED'}>{#each design.nodes as node}<option value={node.id}>{node.label}</option>{/each}</select></label><Button variant="secondary" disabled={pipeline?.state === 'ARCHIVED'} onclick={connect}>Create connection</Button></aside><section class="canvas" aria-label="Pipeline design canvas">{#each design.nodes as node}<button class:selected={selected===node.id} class="node" style={`left:${node.positionX}px;top:${node.positionY}px`} onclick={() => selected=node.id}><strong>{node.label}</strong><small>{node.type}{node.connectorKey ? ` · ${node.connectorKey}` : ''}</small></button>{/each}{#each design.edges as edge}<p class="edge">{edge.sourceNodeId.slice(0,4)} → {edge.targetNodeId.slice(0,4)} {#if pipeline?.state !== 'ARCHIVED'}<button aria-label="Delete connection" onclick={() => deleteEdge(edge.id)}>×</button>{/if}</p>{/each}</section><aside>{#if selected}{@const node=design.nodes.find((item)=>item.id===selected)}{#if node}<h2>Inspector</h2><label>Label<input value={node.label} oninput={updateLabel} disabled={pipeline?.state === 'ARCHIVED'}/></label><p>{node.type}</p>{#if node.type !== 'TRANSFORM'}<label>Connector<select value={node.connectorKey ?? ''} disabled={pipeline?.state === 'ARCHIVED'} onchange={(event)=>{node.connectorKey=event.currentTarget.value; dirty=true;}}>{#each connectors as connector}<option value={connector.key}>{connector.displayName}</option>{/each}</select></label>{/if}<Button variant="danger" disabled={pipeline?.state === 'ARCHIVED'} onclick={removeNode}>Delete node</Button>{/if}{:else}<p>Select a node to inspect it.</p>{/if}</aside></div>{/if}
<style>header{display:flex;justify-content:space-between;align-items:start;margin-bottom:var(--space-4)}h1{margin:0;font-size:1.5rem}header span{color:var(--text-muted);font-size:.8rem}header div:last-child,aside{display:flex;gap:var(--space-2)}.designer{display:grid;grid-template-columns:10rem minmax(30rem,1fr) 14rem;gap:var(--space-3);min-height:33rem}.designer aside{flex-direction:column;border:1px solid var(--border-default);padding:var(--space-3)}h2{margin:0 0 var(--space-2);font-size:.9rem}.canvas{position:relative;min-height:30rem;border:1px solid var(--border-default);background:var(--bg-surface)}.node{position:absolute;display:grid;min-width:9rem;border:1px solid var(--border-strong);border-radius:var(--radius-sm);background:#fff;padding:.5rem;text-align:left}.node.selected{border-color:var(--accent);box-shadow:var(--focus-ring)}.node small,.edge{color:var(--text-muted);font-size:.7rem}.edge{margin:0;padding:.2rem}label{display:grid;gap:.25rem;font-size:.8rem}input,select{min-width:0;padding:.35rem;border:1px solid var(--border-default)}@media(max-width:760px){.designer{display:block}.canvas{min-height:16rem;margin:var(--space-3) 0}.designer aside:first-child{display:none}}</style>
