<script lang="ts">
  import { beforeNavigate,goto } from '$app/navigation'; import { page } from '$app/state'; import { onDestroy,onMount } from 'svelte'; import { SvelteFlowProvider,type Connection } from '@xyflow/svelte';
  import { getPipelineDefinition,getPipelineDesign,listConnections,listNodeTypes,pipelineErrorMessage,runPipeline,savePipelineDesign,validatePipelineDesign,type ConnectionDefinition,type NexetlError,type NodeTypeDefinition,type PipelineDefinition,type PipelineDesign,type PipelineDesignValidationResult,type SchemaField } from '$lib/api/pipelines';
  import { apiDesignToFlow,apiEdgeToFlow,flowNodeToApi,flowToApiDesign } from '$lib/designer/graph-mapping'; import type { PipelineFlowEdge,PipelineFlowNode } from '$lib/designer/graph-model'; import { checkConnection } from '$lib/designer/graph-validation'; import { routeEntity } from '$lib/route-context';
  import Alert from '$lib/components/ui/Alert.svelte'; import Icon from '$lib/components/ui/Icon.svelte'; import PipelineDesignerHeader from '$lib/components/designer/PipelineDesignerHeader.svelte'; import NodePalette from '$lib/components/designer/NodePalette.svelte'; import PipelineCanvas from '$lib/components/designer/PipelineCanvas.svelte'; import NodeInspector from '$lib/components/designer/NodeInspector.svelte';
  type Snapshot={nodes:PipelineFlowNode[];edges:PipelineFlowEdge[]};
  let pipeline=$state<PipelineDefinition|null>(null),persisted=$state<PipelineDesign|null>(null),nodeTypes=$state<NodeTypeDefinition[]>([]),connections=$state<ConnectionDefinition[]>([]);
  let nodes=$state.raw<PipelineFlowNode[]>([]),edges=$state.raw<PipelineFlowEdge[]>([]),selectedNodeId=$state<string|null>(null),selectedEdgeId=$state<string|null>(null),undoStack=$state.raw<Snapshot[]>([]),redoStack=$state.raw<Snapshot[]>([]);
  let loading=$state(true),saving=$state(false),running=$state(false),dirty=$state(false),error=$state(''),conflict=$state(false),validation=$state<PipelineDesignValidationResult|null>(null),fitRequest=$state(0),connectionMessage=$state(''),dragCaptured=$state(false);
  let status=$derived<'saved'|'dirty'|'error'|'conflict'>(conflict?'conflict':error&&persisted?'error':dirty?'dirty':'saved'),selectedNode=$derived(nodes.find(n=>n.id===selectedNodeId)??null),selectedEdge=$derived(edges.find(e=>e.id===selectedEdgeId)??null),readonly=$derived(pipeline?.state==='ARCHIVED');
  const clone=<T,>(value:T):T=>JSON.parse(JSON.stringify(value)) as T; const snapshot=():Snapshot=>({nodes:clone(nodes),edges:clone(edges)});
  function checkpoint(){undoStack=[...undoStack.slice(-49),snapshot()];redoStack=[]}
  function restore(value:Snapshot){nodes=clone(value.nodes);edges=clone(value.edges);selectedNodeId=null;selectedEdgeId=null;changed()}
  function undo(){if(readonly||!undoStack.length)return;const previous=undoStack.at(-1)!;redoStack=[snapshot(),...redoStack];undoStack=undoStack.slice(0,-1);restore(previous)}
  function redo(){if(readonly||!redoStack.length)return;const next=redoStack[0];undoStack=[...undoStack,snapshot()];redoStack=redoStack.slice(1);restore(next)}
  $effect(()=>{const id=page.params.pipelineDefinitionId;if(id)void load(id)}); beforeNavigate(({cancel})=>{if(dirty&&!saving&&!confirm('You have unsaved Pipeline changes. Leave without saving?'))cancel()});
  onMount(()=>{const before=(event:BeforeUnloadEvent)=>{if(dirty){event.preventDefault();event.returnValue=''}};const keys=(event:KeyboardEvent)=>{const modifier=event.ctrlKey||event.metaKey;if(modifier&&event.key.toLowerCase()==='s'){event.preventDefault();if(dirty&&!saving&&!readonly)void save()}if(modifier&&event.key.toLowerCase()==='z'){event.preventDefault();event.shiftKey?redo():undo()}if(modifier&&event.key.toLowerCase()==='d'){event.preventDefault();duplicate()}};window.addEventListener('beforeunload',before);window.addEventListener('keydown',keys);return()=>{window.removeEventListener('beforeunload',before);window.removeEventListener('keydown',keys)}});onDestroy(()=>routeEntity.set(null));
  async function load(id:string){loading=true;error='';try{const[p,d,n,c]=await Promise.all([getPipelineDefinition(id),getPipelineDesign(id),listNodeTypes(),listConnections()]);pipeline=p;routeEntity.set(p.name);persisted=d;nodeTypes=n.items;connections=c.items;const graph=apiDesignToFlow(d,p.state==='ARCHIVED');nodes=graph.nodes;edges=graph.edges;undoStack=[];redoStack=[];dirty=false;validation=null;requestAnimationFrame(()=>fitRequest++)}catch(failure){error=pipelineErrorMessage(failure as NexetlError)}finally{loading=false}}
  function changed(){if(readonly)return;dirty=true;validation=null;error='';conflict=false}
  function selectNode(id:string|null){selectedNodeId=id;selectedEdgeId=null;nodes=nodes.map(node=>({...node,selected:node.id===id}));edges=edges.map(edge=>({...edge,selected:false}))} function selectEdge(id:string|null){selectedEdgeId=id;selectedNodeId=null;edges=edges.map(edge=>({...edge,selected:edge.id===id}));nodes=nodes.map(node=>({...node,selected:false}))} function clearSelection(){selectedNodeId=null;selectedEdgeId=null;nodes=nodes.map(node=>({...node,selected:false}));edges=edges.map(edge=>({...edge,selected:false}))}
  function add(kind:string,position?:{x:number;y:number}){if(readonly)return;const definition=nodeTypes.find(item=>item.key===kind);if(!definition)return;checkpoint();const index=nodes.length,id=crypto.randomUUID(),point=position??{x:80+(index%3)*270,y:80+Math.floor(index/3)*150};nodes=[...nodes,{id,type:'pipeline',position:point,data:{label:definition.displayName,nodeType:definition.category,nodeKind:definition.key,connectorKey:null,configuration:clone(definition.configurationDefaults),inputSchema:[],outputSchema:[],inputPorts:definition.inputs,outputPorts:definition.outputs},draggable:true,connectable:true,deletable:true,selected:true}];changed();selectNode(id)}
  function updateNode(values:Partial<PipelineFlowNode['data']>){if(!selectedNodeId||readonly)return;checkpoint();nodes=nodes.map(node=>node.id===selectedNodeId?{...node,data:{...node.data,...values}}:node);changed()}
  function removeNode(){if(!selectedNodeId||readonly)return;checkpoint();const id=selectedNodeId;nodes=nodes.filter(n=>n.id!==id);edges=edges.filter(e=>e.source!==id&&e.target!==id);selectedNodeId=null;changed()}
  function duplicate(){if(!selectedNode||readonly)return;checkpoint();const id=crypto.randomUUID();nodes=[...nodes,{...clone(selectedNode),id,position:{x:selectedNode.position.x+35,y:selectedNode.position.y+35},selected:true}];changed();selectNode(id)}
  function connect(source:string,target:string,sourcePort?:string,targetPort?:string){if(readonly)return;const candidate={source,target,sourceHandle:sourcePort,targetHandle:targetPort},result=checkConnection(candidate,nodes,edges);if(!result.valid){notify(result.message);return}checkpoint();edges=[...edges,apiEdgeToFlow({id:crypto.randomUUID(),sourceNodeId:source,sourcePort:sourcePort??nodes.find(n=>n.id===source)?.data.outputPorts[0]?.key??'output',targetNodeId:target,targetPort:targetPort??nodes.find(n=>n.id===target)?.data.inputPorts[0]?.key??'input'})];notify('Connection added.');changed()}
  function beforeVisualConnect(connection:Connection):PipelineFlowEdge|false{const result=checkConnection(connection,nodes,edges);if(!result.valid){notify(result.message);return false}checkpoint();changed();return apiEdgeToFlow({id:crypto.randomUUID(),sourceNodeId:connection.source!,sourcePort:connection.sourceHandle??'output',targetNodeId:connection.target!,targetPort:connection.targetHandle??'input'})}
  function notify(message:string){connectionMessage=message;setTimeout(()=>connectionMessage='',2600)} function removeEdge(){if(!selectedEdgeId||readonly)return;checkpoint();edges=edges.filter(e=>e.id!==selectedEdgeId);selectedEdgeId=null;changed()} function removeEdgeById(id:string){if(readonly)return;checkpoint();edges=edges.filter(e=>e.id!==id);changed()} function deleted(deletedNodes:PipelineFlowNode[],deletedEdges:PipelineFlowEdge[]){if(readonly)return;if(deletedNodes.length||deletedEdges.length){selectedNodeId=null;selectedEdgeId=null;changed()}}
  function dragStart(){if(!dragCaptured){checkpoint();dragCaptured=true}} function dragStop(){dragCaptured=false;changed()}
  function arrange(){if(readonly||!nodes.length)return;checkpoint();const indegree=new Map(nodes.map(n=>[n.id,0])),out=new Map(nodes.map(n=>[n.id,[] as string[]]));for(const e of edges){indegree.set(e.target,(indegree.get(e.target)??0)+1);out.get(e.source)?.push(e.target)}const queue=nodes.filter(n=>!indegree.get(n.id)).map(n=>n.id),levels=new Map<string,number>(queue.map(id=>[id,0]));while(queue.length){const id=queue.shift()!;for(const target of out.get(id)??[]){levels.set(target,Math.max(levels.get(target)??0,(levels.get(id)??0)+1));indegree.set(target,(indegree.get(target)??1)-1);if(!indegree.get(target))queue.push(target)}}const rows=new Map<number,number>();nodes=nodes.map((n,i)=>{const level=levels.get(n.id)??i,count=rows.get(level)??0;rows.set(level,count+1);return{...n,position:{x:80+level*280,y:70+count*150}}});changed();requestAnimationFrame(()=>fitRequest++)}
  async function save(){if(!persisted||readonly)return true;saving=true;error='';try{persisted=await savePipelineDesign(persisted.pipelineId,flowToApiDesign(persisted,nodes,edges));const graph=apiDesignToFlow(persisted,false);nodes=graph.nodes;edges=graph.edges;dirty=false;undoStack=[];redoStack=[];return true}catch(failure){const typed=failure as NexetlError;conflict=typed.code==='NEXETL_PIPELINE_DESIGN_REVISION_CONFLICT';error=conflict?'A newer design was saved elsewhere. Reload before continuing.':pipelineErrorMessage(typed);return false}finally{saving=false}}
  async function validate(){if(!persisted)return;if(dirty&&!await save())return;try{validation=await validatePipelineDesign(persisted.pipelineId);if(validation.schemas)nodes=nodes.map(node=>({...node,data:{...node.data,outputSchema:validation?.schemas?.[node.id]??node.data.outputSchema}}))}catch(failure){error=pipelineErrorMessage(failure as NexetlError)}}
  async function run(){if(!persisted)return;running=true;try{if(dirty&&!await save())return;await validate();if(!validation?.valid){error='Resolve validation errors before running this Pipeline.';return}const result=await runPipeline(persisted.pipelineId);dirty=false;await goto(`/pipelines/${persisted.pipelineId}/runs/${result.id}`)}catch(failure){const typed=failure as NexetlError;validation=typed.details?.issues?{valid:false,issues:typed.details.issues}:validation;error=pipelineErrorMessage(typed)}finally{running=false}}
</script>
<svelte:head><title>{pipeline?.name??'Pipeline'} Design | NEXETL</title></svelte:head>
{#if loading}<div class="loading" role="status">Preparing Pipeline Designer…</div>{:else if error&&!persisted}<div class="load-error"><Alert variant="error">{error}</Alert></div>{:else if persisted&&pipeline}<div class="workspace"><div class:has-notice={Boolean(error)} class="desktop-workspace"><PipelineDesignerHeader {pipeline} revision={persisted.revision} {status} {saving} {running} canUndo={undoStack.length>0} canRedo={redoStack.length>0} onfit={()=>fitRequest++} onvalidate={validate} onsave={save} onrun={run} onundo={undo} onredo={redo} onarrange={arrange} onduplicate={duplicate}/>{#if error}<div class:conflict class="notice" role="alert"><Icon name="check" size={17}/><span>{error}</span>{#if conflict}<button onclick={()=>load(persisted!.pipelineId)}>Reload latest</button>{/if}</div>{/if}<div class="designer-grid"><NodePalette {readonly} {nodeTypes} onadd={(kind)=>add(kind)}/><SvelteFlowProvider><PipelineCanvas bind:nodes bind:edges {readonly} {fitRequest} {connectionMessage} onselectnode={selectNode} onselectedge={selectEdge} onclear={clearSelection} onbeforeconnect={beforeVisualConnect} onconnected={()=>notify('Connection added.')} ondragstart={dragStart} ondragstop={dragStop} ondelete={deleted} ondropnode={add}/></SvelteFlowProvider><NodeInspector node={selectedNode?flowNodeToApi(selectedNode):null} selectedEdge={selectedEdge?{id:selectedEdge.id,sourceNodeId:selectedEdge.source,sourcePort:selectedEdge.sourceHandle??'output',targetNodeId:selectedEdge.target,targetPort:selectedEdge.targetHandle??'input'}:null} nodes={nodes.map(flowNodeToApi)} edges={edges.map(e=>({id:e.id,sourceNodeId:e.source,sourcePort:e.sourceHandle??'output',targetNodeId:e.target,targetPort:e.targetHandle??'input'}))} pipelineName={pipeline.name} pipelineState={pipeline.state} {connections} revision={persisted.revision} {readonly} {validation} onLabel={(label)=>updateNode({label})} onConfiguration={(configuration)=>updateNode({configuration})} onConnector={(connectorKey)=>updateNode({connectorKey})} onSchema={(outputSchema:SchemaField[])=>updateNode({outputSchema})} onDeleteNode={removeNode} onDeleteEdge={removeEdge} onDeleteEdgeById={removeEdgeById} onConnect={connect} onSelectNode={selectNode}/></div></div><div class="mobile-limitation"><h1>Use a larger screen to edit this Pipeline.</h1><p>Run history and settings remain available on smaller screens.</p><a href={`/pipelines/${pipeline.id}`}>View Pipeline overview</a></div></div>{/if}
<style>.workspace{height:100%;min-height:0;overflow:hidden;background:var(--bg-canvas)}.desktop-workspace{display:grid;height:100%;min-height:0;grid-template-rows:auto minmax(0,1fr);overflow:hidden}.desktop-workspace.has-notice{grid-template-rows:auto auto minmax(0,1fr)}.designer-grid{display:grid;min-height:0;overflow:hidden;grid-template-columns:238px minmax(360px,1fr) 330px}.notice{z-index:7;display:flex;align-items:center;gap:.6rem;border-bottom:1px solid #f0d0cd;background:#fff3f2;padding:.58rem 1rem;color:var(--danger);font-size:.72rem}.notice button{margin-left:auto}.notice.conflict{background:#fff8ed;color:var(--warning)}.loading{display:grid;height:100%;place-items:center;color:var(--text-muted)}.load-error{padding:2rem}.mobile-limitation{display:none}@media(max-width:1100px) and (min-width:769px){.designer-grid{grid-template-columns:190px minmax(300px,1fr) 280px}}@media(max-width:768px){.desktop-workspace{display:none}.mobile-limitation{display:grid;height:100%;place-content:center;justify-items:center;padding:2rem;text-align:center}.mobile-limitation h1{font-size:1.1rem}.mobile-limitation p{color:var(--text-muted);font-size:.8rem}}</style>
