<script lang="ts">
  import { page } from '$app/state';
  import { getPipelineDefinition,getPipelineDesign,listConnectors,pipelineErrorMessage,savePipelineDesign,validatePipelineDesign,type ConnectorDefinition,type NexetlError,type PipelineDefinition,type PipelineDesign,type PipelineDesignNodeType,type PipelineDesignValidationResult } from '$lib/api/pipelines';
  import Alert from '$lib/components/ui/Alert.svelte'; import Icon from '$lib/components/ui/Icon.svelte';
  import PipelineDesignerHeader from '$lib/components/designer/PipelineDesignerHeader.svelte'; import NodePalette from '$lib/components/designer/NodePalette.svelte'; import PipelineCanvas from '$lib/components/designer/PipelineCanvas.svelte'; import NodeInspector from '$lib/components/designer/NodeInspector.svelte';
  let pipeline=$state<PipelineDefinition|null>(null),design=$state<PipelineDesign|null>(null),connectors=$state<ConnectorDefinition[]>([]),selectedNodeId=$state<string|null>(null),selectedEdgeId=$state<string|null>(null),loading=$state(true),saving=$state(false),dirty=$state(false),error=$state(''),conflict=$state(false),validation=$state<PipelineDesignValidationResult|null>(null),fitRequest=$state(0);
  let status=$derived<'saved'|'dirty'|'error'|'conflict'>(conflict?'conflict':error&&design?'error':dirty?'dirty':'saved');
  let selectedNode=$derived(design?.nodes.find(n=>n.id===selectedNodeId)??null),selectedEdge=$derived(design?.edges.find(e=>e.id===selectedEdgeId)??null),readonly=$derived(pipeline?.state==='ARCHIVED');
  $effect(()=>{const id=page.params.pipelineDefinitionId;if(id)void load(id)});
  async function load(id:string){loading=true;error='';conflict=false;validation=null;try{const[p,d,c]=await Promise.all([getPipelineDefinition(id),getPipelineDesign(id),listConnectors()]);pipeline=p;design=d;connectors=c.items.filter(item=>item.availability==='AVAILABLE');selectedNodeId=null;selectedEdgeId=null;dirty=false;requestAnimationFrame(()=>fitRequest++)}catch(failure){error=pipelineErrorMessage(failure as NexetlError)}finally{loading=false}}
  function change(mutator:(current:PipelineDesign)=>PipelineDesign){if(!design||readonly)return;design=mutator(design);dirty=true;validation=null;error='';conflict=false}
  function add(type:PipelineDesignNodeType){const connector=type==='TRANSFORM'?null:connectors[0]?.key??null;const index=design?.nodes.length??0;const id=crypto.randomUUID();change(current=>({...current,nodes:[...current.nodes,{id,type,label:type==='TRANSFORM'?'Transform':`${connectors.find(c=>c.key===connector)?.displayName??type} ${type==='SOURCE'?'Source':'Target'}`,connectorKey:connector,positionX:90+(index%3)*240,positionY:85+Math.floor(index/3)*130}]}));selectedNodeId=id;selectedEdgeId=null}
  function moveNode(id:string,x:number,y:number){change(current=>({...current,nodes:current.nodes.map(node=>node.id===id?{...node,positionX:Math.round(x),positionY:Math.round(y)}:node)}))}
  function updateNode(values:Partial<{label:string;connectorKey:string}>){if(!selectedNodeId)return;change(current=>({...current,nodes:current.nodes.map(node=>node.id===selectedNodeId?{...node,...values}:node)}))}
  function removeNode(){if(!selectedNodeId)return;const id=selectedNodeId;change(current=>({...current,nodes:current.nodes.filter(n=>n.id!==id),edges:current.edges.filter(e=>e.sourceNodeId!==id&&e.targetNodeId!==id)}));selectedNodeId=null}
  function connect(sourceNodeId:string,targetNodeId:string){if(!design||sourceNodeId===targetNodeId||design.edges.some(e=>e.sourceNodeId===sourceNodeId&&e.targetNodeId===targetNodeId))return;change(current=>({...current,edges:[...current.edges,{id:crypto.randomUUID(),sourceNodeId,targetNodeId}]}))}
  function removeEdge(){if(!selectedEdgeId)return;const id=selectedEdgeId;change(current=>({...current,edges:current.edges.filter(e=>e.id!==id)}));selectedEdgeId=null}
  async function save():Promise<boolean>{if(!design||readonly)return true;saving=true;error='';conflict=false;try{design=await savePipelineDesign(design.pipelineId,design);dirty=false;return true}catch(failure){const typed=failure as NexetlError;conflict=typed.code==='NEXETL_PIPELINE_DESIGN_REVISION_CONFLICT';error=conflict?'A newer version of this Pipeline Design exists. Your local changes were not automatically overwritten.':pipelineErrorMessage(typed);return false}finally{saving=false}}
  async function validate(){if(!design)return;if(dirty&&!await save())return;error='';try{validation=await validatePipelineDesign(design.pipelineId)}catch(failure){error=pipelineErrorMessage(failure as NexetlError)}}
</script>
<svelte:head><title>{pipeline?.name??'Pipeline'} Design | NEXETL</title></svelte:head>
{#if loading}<div class="loading" role="status"><span></span>Preparing Pipeline Designer…</div>{:else if error&&!design}<div class="load-error"><Alert variant="error">{error}</Alert></div>{:else if design&&pipeline}
  <div class="workspace"><div class="desktop-workspace"><PipelineDesignerHeader {pipeline} revision={design.revision} {status} {saving} onfit={()=>fitRequest++} onvalidate={validate} onsave={save}/>
    {#if error}<div class:conflict class="notice" role="alert"><Icon name="check" size={17}/><span>{error}</span>{#if conflict}<button onclick={()=>load(design!.pipelineId)}>Reload latest</button>{/if}</div>{/if}
    <div class="designer-grid"><NodePalette {readonly} onadd={add}/><PipelineCanvas nodes={design.nodes} edges={design.edges} {selectedNodeId} {selectedEdgeId} {readonly} {fitRequest} onSelectNode={(id)=>{selectedNodeId=id;selectedEdgeId=null}} onSelectEdge={(id)=>{selectedEdgeId=id;selectedNodeId=null}} onMoveNode={moveNode}/><NodeInspector node={selectedNode} {selectedEdge} nodes={design.nodes} edgeCount={design.edges.length} {connectors} revision={design.revision} {readonly} {validation} onLabel={(label)=>updateNode({label})} onConnector={(connectorKey)=>updateNode({connectorKey})} onDeleteNode={removeNode} onDeleteEdge={removeEdge} onConnect={connect} onSelectNode={(id)=>{selectedNodeId=id;selectedEdgeId=null}}/></div></div>
    <div class="mobile-limitation"><span><Icon name="pipelines" size={24}/></span><h1>Pipeline Designer works best on a larger screen.</h1><p>You can still inspect this Pipeline from its details page.</p><a href={`/pipelines/${pipeline.id}`}>View Pipeline details</a></div>
  </div>
{/if}
<style>.workspace{height:calc(100vh - var(--topbar-height));background:var(--bg-canvas)}.desktop-workspace{display:grid;height:100%;grid-template-rows:auto auto minmax(0,1fr)}.designer-grid{display:grid;min-height:0;grid-template-columns:232px minmax(420px,1fr) 296px}.notice{z-index:7;display:flex;align-items:center;gap:.6rem;border-bottom:1px solid #f0d0cd;background:#fff3f2;padding:.58rem 1rem;color:var(--danger);font-size:.72rem}.notice button{margin-left:auto;border:1px solid currentColor;border-radius:var(--radius-sm);background:transparent;padding:.28rem .55rem;color:inherit;font-size:.68rem;font-weight:650;cursor:pointer}.notice.conflict{background:#fff8ed;color:var(--warning);border-color:#f0dbb9}.loading{display:flex;height:calc(100vh - var(--topbar-height));align-items:center;justify-content:center;gap:.65rem;color:var(--text-muted)}.loading span{width:1rem;height:1rem;border:2px solid var(--border-default);border-top-color:var(--accent);border-radius:50%;animation:spin .7s linear infinite}.load-error{padding:2rem}.mobile-limitation{display:none}@keyframes spin{to{transform:rotate(360deg)}}@media(max-width:1100px) and (min-width:641px){.designer-grid{grid-template-columns:190px minmax(360px,1fr) 260px}}@media(max-width:640px){.desktop-workspace{display:none}.mobile-limitation{display:grid;height:100%;place-content:center;justify-items:center;padding:2rem;text-align:center}.mobile-limitation span{display:grid;width:3.5rem;height:3.5rem;place-items:center;border:1px solid var(--border-default);border-radius:var(--radius-lg);background:#fff;color:var(--accent)}.mobile-limitation h1{max-width:22rem;margin:1rem 0 .4rem;font-size:1.1rem}.mobile-limitation p{margin:0 0 1rem;color:var(--text-muted);font-size:.8rem}.mobile-limitation a{border:1px solid var(--border-default);border-radius:var(--radius-sm);background:#fff;padding:.5rem .75rem;font-size:.75rem;font-weight:650}}
</style>
