<script lang="ts">
  import { onMount } from 'svelte'; import { listConnectors, pipelineErrorMessage, type ConnectorDefinition, type NexetlError } from '$lib/api/pipelines'; import PageHeader from '$lib/components/ui/PageHeader.svelte'; import Alert from '$lib/components/ui/Alert.svelte'; import Icon from '$lib/components/ui/Icon.svelte';
  let items = $state<ConnectorDefinition[]>([]), loading = $state(true), error = $state(''), search = $state(''), category = $state('');
  onMount(async () => { try { items = (await listConnectors()).items; } catch (failure) { error = pipelineErrorMessage(failure as NexetlError); } finally { loading = false; } });
  let filtered = $derived(items.filter((item) => (!category || item.category === category) && `${item.displayName} ${item.vendor} ${item.description}`.toLowerCase().includes(search.toLowerCase())));
</script>
<svelte:head><title>Connectors | NEXETL</title></svelte:head>
<PageHeader title="Connectors" description="Browse connector types available to Pipeline authoring." />
<div class="toolbar"><label>Search<input bind:value={search} placeholder="Search connectors…" /></label><label>Capability<select bind:value={category}><option value="">All capabilities</option><option value="SOURCE">Source</option><option value="TARGET">Target</option><option value="BOTH">Source + Target</option></select></label></div>{#if loading}<p role="status">Loading connector catalogue…</p>{:else if error}<Alert variant="error">{error}</Alert>{:else}<div class="catalogue-heading"><p class="eyebrow">Connector catalogue</p><span>{filtered.length} available</span></div><section class="grid">{#each filtered as connector}<a href={`/connectors/${connector.key}`}><span class="icon"><Icon name="database" size={19}/></span><div><div class="connector-title"><h2>{connector.displayName}</h2><span class:unavailable={connector.availability!=='AVAILABLE'}>{connector.availability === 'AVAILABLE' ? 'Available' : 'Coming later'}</span></div><small>{connector.vendor} · {connector.category==='BOTH'?'Source + Target':connector.category}</small><p>{connector.description}</p></div><Icon name="chevron-right" size={16}/></a>{/each}</section>{#if !filtered.length}<p class="empty">No matching connectors.</p>{/if}{/if}
<style>.toolbar{display:flex;gap:.65rem;margin-bottom:1.5rem}.toolbar label{display:grid;gap:.25rem;color:var(--text-muted);font-size:.63rem;font-weight:650}.toolbar label:first-child{width:min(24rem,60%)}input,select{height:2.25rem;border:1px solid var(--border-default);border-radius:var(--radius-sm);background:#fff;padding:0 .6rem;color:var(--text-primary);font-size:.72rem}.catalogue-heading{display:flex;align-items:center;justify-content:space-between;margin-bottom:.55rem}.catalogue-heading span{color:var(--text-muted);font-size:.64rem}.grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:.7rem}.grid>a{display:grid;grid-template-columns:2.5rem 1fr auto;align-items:start;gap:.8rem;border:1px solid var(--border-default);border-radius:var(--radius-md);background:#fff;padding:1rem;color:var(--text-primary);box-shadow:var(--shadow-sm)}.grid>a:hover{border-color:#b6c0ce;box-shadow:0 5px 16px rgb(20 31 50 / 8%)}.grid>a>:global(svg){align-self:center;color:var(--text-muted)}.icon{display:grid;width:2.5rem;height:2.5rem;place-items:center;border-radius:7px;background:var(--accent-soft);color:var(--accent)}.connector-title{display:flex;align-items:center;justify-content:space-between;gap:.7rem}.connector-title h2{margin:0;font-size:.82rem}.connector-title span{border-radius:999px;background:#e9f6f1;color:var(--success);padding:.1rem .42rem;font-size:.57rem;font-weight:700}.connector-title span.unavailable{background:var(--bg-subtle);color:var(--text-muted)}.grid small{display:block;margin-top:.15rem;color:var(--text-muted);font-size:.62rem}.grid p{margin:.45rem 0 0;color:var(--text-secondary);font-size:.69rem;line-height:1.45}.empty{border:1px dashed var(--border-default);padding:2rem;text-align:center;color:var(--text-muted)}@media(max-width:760px){.grid{grid-template-columns:1fr}.toolbar{flex-wrap:wrap}.toolbar label:first-child{width:100%}}</style>
