<script lang="ts">
  import { onMount } from 'svelte'; import { listConnectors, pipelineErrorMessage, type ConnectorDefinition, type NexetlError } from '$lib/api/pipelines'; import PageHeader from '$lib/components/ui/PageHeader.svelte'; import Alert from '$lib/components/ui/Alert.svelte';
  let items = $state<ConnectorDefinition[]>([]), loading = $state(true), error = $state(''), search = $state(''), category = $state('');
  onMount(async () => { try { items = (await listConnectors()).items; } catch (failure) { error = pipelineErrorMessage(failure as NexetlError); } finally { loading = false; } });
  let filtered = $derived(items.filter((item) => (!category || item.category === category) && `${item.displayName} ${item.vendor} ${item.description}`.toLowerCase().includes(search.toLowerCase())));
</script>
<svelte:head><title>Connectors | NEXETL</title></svelte:head>
<PageHeader title="Connectors" description="Browse connector types available to Pipeline authoring." />
<div class="toolbar"><label>Search <input bind:value={search} placeholder="Find connectors" /></label><label>Category <select bind:value={category}><option value="">All</option><option value="SOURCE">Source</option><option value="TARGET">Target</option><option value="BOTH">Both</option></select></label></div>{#if loading}<p role="status">Loading connector catalogue…</p>{:else if error}<Alert variant="error">{error}</Alert>{:else}<p class="caption">Connector catalogue</p><section class="grid">{#each filtered as connector}<a href={`/connectors/${connector.key}`}><span class="icon">{connector.displayName.slice(0, 2)}</span><div><h2>{connector.displayName}</h2><small>{connector.vendor} · {connector.category} · {connector.availability === 'AVAILABLE' ? 'Available' : 'Coming later'}</small><p>{connector.description}</p></div></a>{/each}</section>{#if !filtered.length}<p>No matching connectors.</p>{/if}{/if}
<style>.toolbar{display:flex;gap:var(--space-3);margin-bottom:var(--space-5)}label{display:grid;gap:.25rem;color:var(--text-muted);font-size:.78rem}input,select{min-height:2.25rem;border:1px solid var(--border-default);border-radius:var(--radius-sm);padding:.35rem .5rem}.caption{color:var(--text-muted);font-size:.8rem}.grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));border-top:1px solid var(--border-default)}.grid a{display:flex;gap:var(--space-3);border-bottom:1px solid var(--border-default);padding:var(--space-4);color:var(--text-primary)}.grid a:hover{background:var(--bg-surface-subtle);text-decoration:none}.icon{display:grid;width:2.4rem;height:2.4rem;place-items:center;border-radius:var(--radius-sm);background:var(--accent-subtle);color:var(--accent);font-size:.7rem;font-weight:700}.grid h2{margin:0;font-size:1rem}.grid small{color:var(--text-muted)}.grid p{margin:.35rem 0 0;color:var(--text-secondary);font-size:.84rem}@media(max-width:700px){.grid{grid-template-columns:1fr}}</style>
