<script lang="ts">
  import { goto } from '$app/navigation'; import { page } from '$app/state';
  import { archivePipelineDefinition, getPipelineDefinition, pipelineErrorMessage, updatePipelineDefinition, type NexetlError, type PipelineDefinition } from '$lib/api/pipelines'; import { formatTimestamp } from '$lib/format';
  import Alert from '$lib/components/ui/Alert.svelte'; import LoadingState from '$lib/components/ui/LoadingState.svelte'; import PageHeader from '$lib/components/ui/PageHeader.svelte'; import Button from '$lib/components/ui/Button.svelte'; import StatusBadge from '$lib/components/ui/StatusBadge.svelte'; import ConfirmDialog from '$lib/components/ui/ConfirmDialog.svelte';
  let definition = $state<PipelineDefinition | null>(null), message = $state(''), loading = $state(true), editing = $state(false), name = $state(''), description = $state(''), pending = $state(false), confirming = $state(false);
  $effect(() => { const id = page.params.pipelineDefinitionId; if (id) void load(id); });
  async function load(id: string) { loading = true; message = ''; try { definition = await getPipelineDefinition(id); name = definition.name; description = definition.description; } catch (failure) { const error = failure as NexetlError; message = pipelineErrorMessage(error); if (error.code === 'NEXETL_AUTHENTICATION_REQUIRED') await goto(`/login?next=${encodeURIComponent(page.url.pathname)}`); } finally { loading = false; } }
  async function save() { if (!definition || !name.trim() || name.trim().length > 120 || description.length > 1000) { message = 'Please review the information and try again.'; return; } pending = true; try { definition = await updatePipelineDefinition(definition.id, name.trim(), description.trim()); editing = false; } catch (failure) { message = pipelineErrorMessage(failure as NexetlError); } finally { pending = false; } }
  async function archive() { if (!definition) return; pending = true; try { definition = await archivePipelineDefinition(definition.id); confirming = false; } catch (failure) { message = pipelineErrorMessage(failure as NexetlError); } finally { pending = false; } }
</script>
<svelte:head><title>{definition?.name ?? 'Pipeline'} | NEXETL</title></svelte:head>
{#if loading}<LoadingState />{:else if message && !definition}<Alert variant="error">{message}</Alert>{:else if definition}<PageHeader title={definition.name} description="Pipeline Definition details." />{#if message}<Alert variant="error">{message}</Alert>{/if}<section class="actions"><a class="design-link" href={`/pipelines/${definition.id}/design`}>{definition.state === 'DRAFT' ? 'Design' : 'View design'}</a>{#if definition.state === 'DRAFT'}<Button variant="secondary" onclick={() => editing = !editing}>{editing ? 'Cancel edit' : 'Edit'}</Button><Button variant="danger" onclick={() => confirming = true}>Archive</Button>{/if}</section>{#if definition.state === 'ARCHIVED'}<Alert variant="info">Archived Pipeline Definitions are read-only.</Alert>{/if}{#if editing}<form onsubmit={(event) => { event.preventDefault(); void save(); }}><label>Pipeline name <input bind:value={name} maxlength="120" required /></label><label>Description <textarea bind:value={description} maxlength="1000"></textarea></label><Button type="submit" loading={pending}>Save changes</Button></form>{/if}<dl><div><dt>State</dt><dd><StatusBadge state={definition.state}/></dd></div><div><dt>Description</dt><dd>{definition.description || 'No description'}</dd></div><div><dt>Pipeline Definition ID</dt><dd><code>{definition.id}</code></dd></div><div><dt>Created</dt><dd>{formatTimestamp(definition.createdAt)}</dd></div><div><dt>Updated</dt><dd>{formatTimestamp(definition.updatedAt)}</dd></div></dl><ConfirmDialog open={confirming} title="Archive Pipeline?" message="Archived Pipeline Definitions remain available for inspection but cannot be edited." pending={pending} onconfirm={archive} oncancel={() => confirming = false}/>{/if}
<style>.actions{display:flex;justify-content:flex-end;gap:var(--space-2);margin:-5rem 0 var(--space-5)}form{display:grid;gap:var(--space-3);max-width:44rem;border-block:1px solid var(--border-default);padding:var(--space-4) 0}label{display:grid;gap:.35rem;font-weight:600}input,textarea{border:1px solid var(--border-default);border-radius:var(--radius-sm);padding:.55rem;font:inherit}textarea{min-height:6rem}dl{max-width:48rem;border-top:1px solid var(--border-default);margin:var(--space-5) 0}dl div{display:grid;grid-template-columns:11rem 1fr;gap:var(--space-4);border-bottom:1px solid var(--border-default);padding:var(--space-3) 0}dt{color:var(--text-muted)}dd{margin:0}code{font-family:var(--font-mono);overflow-wrap:anywhere}@media(max-width:600px){.actions{margin:0 0 var(--space-4)}dl div{grid-template-columns:1fr;gap:.25rem}}</style>
