<script lang="ts">
  import { goto } from '$app/navigation'; import { page } from '$app/state';
  import { archivePipelineDefinition, getPipelineDefinition, pipelineErrorMessage, updatePipelineDefinition, type NexetlError, type PipelineDefinition } from '$lib/api/pipelines'; import { formatTimestamp } from '$lib/format';
  import Alert from '$lib/components/ui/Alert.svelte'; import LoadingState from '$lib/components/ui/LoadingState.svelte'; import Button from '$lib/components/ui/Button.svelte'; import StatusBadge from '$lib/components/ui/StatusBadge.svelte'; import ConfirmDialog from '$lib/components/ui/ConfirmDialog.svelte'; import Icon from '$lib/components/ui/Icon.svelte';
  let definition = $state<PipelineDefinition | null>(null), message = $state(''), loading = $state(true), editing = $state(false), name = $state(''), description = $state(''), pending = $state(false), confirming = $state(false);
  $effect(() => { const id = page.params.pipelineDefinitionId; if (id) void load(id); });
  async function load(id: string) { loading = true; message = ''; try { definition = await getPipelineDefinition(id); name = definition.name; description = definition.description; } catch (failure) { const error = failure as NexetlError; message = pipelineErrorMessage(error); if (error.code === 'NEXETL_AUTHENTICATION_REQUIRED') await goto(`/login?next=${encodeURIComponent(page.url.pathname)}`); } finally { loading = false; } }
  async function save() { if (!definition || !name.trim() || name.trim().length > 120 || description.length > 1000) { message = 'Please review the information and try again.'; return; } pending = true; try { definition = await updatePipelineDefinition(definition.id, name.trim(), description.trim()); editing = false; } catch (failure) { message = pipelineErrorMessage(failure as NexetlError); } finally { pending = false; } }
  async function archive() { if (!definition) return; pending = true; try { definition = await archivePipelineDefinition(definition.id); confirming = false; } catch (failure) { message = pipelineErrorMessage(failure as NexetlError); } finally { pending = false; } }
</script>
<svelte:head><title>{definition?.name ?? 'Pipeline'} | NEXETL</title></svelte:head>
{#if loading}<LoadingState />{:else if message && !definition}<Alert variant="error">{message}</Alert>{:else if definition}<a class="back" href="/pipelines"><Icon name="arrow-left" size={15}/>Pipelines</a><header class="detail-header"><div><div class="title-line"><h1>{definition.name}</h1><StatusBadge state={definition.state}/></div><p>Pipeline Definition</p></div><div class="actions"><a class="design-link" href={`/pipelines/${definition.id}/design`}><Icon name="pipelines" size={15}/>{definition.state === 'DRAFT' ? 'Design' : 'View design'}</a>{#if definition.state === 'DRAFT'}<Button variant="secondary" onclick={() => editing = !editing}>{editing ? 'Cancel edit' : 'Edit'}</Button><Button variant="secondary" onclick={() => confirming = true}>Archive</Button>{/if}</div></header>{#if message}<Alert variant="error">{message}</Alert>{/if}{#if definition.state === 'ARCHIVED'}<Alert variant="info">Archived Pipeline Definitions are read only. The saved design remains available for inspection.</Alert>{/if}{#if editing}<form onsubmit={(event) => { event.preventDefault(); void save(); }}><label>Pipeline name <input bind:value={name} maxlength="120" required /></label><label>Description <textarea bind:value={description} maxlength="1000"></textarea></label><div><Button type="submit" loading={pending}>Save changes</Button></div></form>{/if}<section class="overview"><p class="eyebrow">Overview</p><dl><div class="wide"><dt>Description</dt><dd>{definition.description || 'No description provided.'}</dd></div><div><dt>Pipeline ID</dt><dd><code>{definition.id}</code></dd></div><div><dt>Created</dt><dd>{formatTimestamp(definition.createdAt)}</dd></div><div><dt>Updated</dt><dd>{formatTimestamp(definition.updatedAt)}</dd></div></dl></section><ConfirmDialog open={confirming} title="Archive Pipeline?" message="Archived Pipeline Definitions remain available for inspection but cannot be edited." pending={pending} onconfirm={archive} oncancel={() => confirming = false}/>{/if}
<style>.back{display:inline-flex;align-items:center;gap:.35rem;margin-bottom:1rem;color:var(--text-muted);font-size:.7rem;font-weight:600}.back:hover{color:var(--accent)}.detail-header{display:flex;align-items:flex-start;justify-content:space-between;gap:1rem;margin-bottom:1.5rem}.title-line{display:flex;align-items:center;gap:.7rem}.detail-header h1{margin:0;font-size:1.5rem;line-height:1.25}.detail-header p{margin:.3rem 0 0;color:var(--text-muted);font-size:.72rem}.actions{display:flex;gap:.5rem}.design-link{display:inline-flex;height:2.25rem;align-items:center;gap:.4rem;border-radius:var(--radius-sm);background:var(--accent);padding:0 .75rem;color:#fff;font-size:.78rem;font-weight:650}.design-link:hover{background:var(--accent-hover)}form{display:grid;gap:.75rem;max-width:44rem;margin:1rem 0;border:1px solid var(--border-default);border-radius:var(--radius-md);background:#fff;padding:1rem}label{display:grid;gap:.3rem;color:var(--text-secondary);font-size:.7rem;font-weight:650}input,textarea{border:1px solid var(--border-default);border-radius:var(--radius-sm);padding:.55rem;font:inherit;font-size:.76rem}textarea{min-height:6rem}.overview{max-width:56rem;margin-top:1.5rem}.overview>.eyebrow{margin-bottom:.6rem}dl{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));margin:0;border:1px solid var(--border-default);border-radius:var(--radius-md);background:#fff;overflow:hidden}dl div{padding:.85rem 1rem;border-bottom:1px solid var(--border-subtle)}dl div:nth-child(even){border-left:1px solid var(--border-subtle)}dl .wide{grid-column:1/-1;border-left:0}dt{margin-bottom:.25rem;color:var(--text-muted);font-size:.62rem;font-weight:650;text-transform:uppercase;letter-spacing:.06em}dd{margin:0;color:var(--text-secondary);font-size:.75rem}code{font-family:var(--font-mono);font-size:.66rem;overflow-wrap:anywhere}@media(max-width:650px){.detail-header{display:block}.actions{margin-top:1rem;flex-wrap:wrap}dl{grid-template-columns:1fr}dl div:nth-child(even){border-left:0}}</style>
