<script lang="ts">
  import type { PipelineDesignEdge, PipelineDesignNode } from '$lib/api/pipelines'; import Icon from '$lib/components/ui/Icon.svelte';
  let { nodes, edges, readonly, onconnect, ondelete }: { nodes: PipelineDesignNode[]; edges:PipelineDesignEdge[]; readonly: boolean; onconnect: (source: string, target: string) => void; ondelete:(id:string)=>void } = $props();
  let source=$state(''),target=$state('');
  let sources=$derived(nodes.filter(n=>n.type!=='TARGET')),targets=$derived(nodes.filter(n=>n.type!=='SOURCE'));
  const labelFor=(id:string)=>nodes.find(node=>node.id===id)?.label??id;
</script>
<details class="connection-editor"><summary><span><Icon name="pipelines" size={15}/>Connections</span><Icon name="chevron-right" size={14}/></summary><div class="fields"><label>From<select bind:value={source} disabled={readonly}><option value="">Select source</option>{#each sources as node}<option value={node.id}>{node.label}</option>{/each}</select></label><label>To<select bind:value={target} disabled={readonly}><option value="">Select target</option>{#each targets as node}<option value={node.id}>{node.label}</option>{/each}</select></label><button disabled={readonly||!source||!target||source===target} onclick={()=>{onconnect(source,target);source='';target=''}}>Connect nodes</button>{#if edges.length}<ul aria-label="Pipeline connections">{#each edges as edge}<li><span>{labelFor(edge.sourceNodeId)} <b>→</b> {labelFor(edge.targetNodeId)}</span>{#if !readonly}<button class="remove" aria-label={`Delete connection from ${labelFor(edge.sourceNodeId)} to ${labelFor(edge.targetNodeId)}`} onclick={()=>ondelete(edge.id)}><Icon name="trash" size={13}/></button>{/if}</li>{/each}</ul>{/if}</div></details>
<style>.connection-editor{border-top:1px solid var(--border-default)}summary{display:flex;align-items:center;justify-content:space-between;padding:.8rem 1rem;color:var(--text-secondary);font-size:.7rem;font-weight:700;text-transform:uppercase;letter-spacing:.06em;cursor:pointer;list-style:none}summary span{display:flex;align-items:center;gap:.45rem}details[open] summary :global(svg:last-child){transform:rotate(90deg)}.fields{display:grid;gap:.65rem;padding:0 1rem 1rem}label{display:grid;gap:.25rem;color:var(--text-muted);font-size:.66rem;font-weight:600}select{min-width:0;height:2rem;border:1px solid var(--border-default);border-radius:var(--radius-sm);background:#fff;padding:0 .45rem;color:var(--text-primary);font-size:.7rem}.fields>button{height:2rem;border:1px solid var(--border-default);border-radius:var(--radius-sm);background:#fff;color:var(--text-secondary);font-size:.7rem;font-weight:650;cursor:pointer}.fields>button:hover:not(:disabled){border-color:var(--accent);color:var(--accent)}.fields button:disabled{opacity:.55;cursor:not-allowed}ul{display:grid;gap:.35rem;margin:.25rem 0 0;padding:.6rem 0 0;border-top:1px solid var(--border-default);list-style:none}li{display:flex;align-items:center;justify-content:space-between;gap:.4rem;color:var(--text-secondary);font-size:.62rem}li span{overflow:hidden;text-overflow:ellipsis;white-space:nowrap}li b{color:var(--accent)}.remove{display:grid;width:1.65rem;height:1.65rem;flex:none;place-items:center;border:0;border-radius:5px;background:transparent;color:var(--danger);cursor:pointer}.remove:hover{background:#fff0ef}</style>
