<script lang="ts">
  import { discoverDatasets,discoverDatasetSchema,discoverSchemas,pipelineErrorMessage,previewDataset,type ConnectionDefinition,type NexetlError,type PipelineDesignNode,type SchemaField } from '$lib/api/pipelines';
  import Button from '$lib/components/ui/Button.svelte';
  let {node,connections,readonly,onchange,onconnector,onschema}:{node:PipelineDesignNode;connections:ConnectionDefinition[];readonly:boolean;onchange:(configuration:Record<string,unknown>)=>void;onconnector:(key:string|null)=>void;onschema:(schema:SchemaField[])=>void}=$props();
  let schemas=$state<string[]>([]),datasets=$state<Array<{name:string;type:string}>>([]),preview=$state<Array<Record<string,unknown>>>([]),busy=$state(false),message=$state('');
  const config=$derived(node.configuration);
  function set(key:string,value:unknown){onchange({...config,[key]:value})}
  function text(key:string){const value=config[key];return typeof value==='string'?value:''}
  function number(key:string,fallback=0){const value=config[key];return typeof value==='number'?value:fallback}
  function json(key:string){return JSON.stringify(config[key]??[],null,2)}
  function setJson(key:string,value:string){try{set(key,JSON.parse(value));message=''}catch{message=`${key} must contain valid JSON.`}}
  async function chooseConnection(id:string){const connection=connections.find(item=>item.id===id);set('connectionId',id);onconnector(connection?.connectorKey??null);schemas=[];datasets=[];preview=[]}
  async function loadSchemas(){const id=text('connectionId');if(!id)return;busy=true;message='';try{schemas=(await discoverSchemas(id)).items}catch(error){message=pipelineErrorMessage(error as NexetlError)}finally{busy=false}}
  async function loadDatasets(){const id=text('connectionId'),schema=text('schema');if(!id||!schema)return;busy=true;try{datasets=(await discoverDatasets(id,schema)).items}catch(error){message=pipelineErrorMessage(error as NexetlError)}finally{busy=false}}
  async function loadSchema(){const id=text('connectionId'),schema=text('schema'),dataset=text('dataset');if(!id||!schema||!dataset)return;busy=true;try{const result=await discoverDatasetSchema(id,schema,dataset);onschema(result.fields);set('schemaFields',result.fields)}catch(error){message=pipelineErrorMessage(error as NexetlError)}finally{busy=false}}
  async function loadPreview(){const id=text('connectionId'),schema=text('schema'),dataset=text('dataset');if(!id||!schema||!dataset)return;busy=true;try{preview=(await previewDataset(id,schema,dataset,50)).rows}catch(error){message=pipelineErrorMessage(error as NexetlError)}finally{busy=false}}
</script>

{#if ['database_source','sql_query_source','database_target'].includes(node.kind)}
  <p class="section-label">Connection</p><label>Connection<select disabled={readonly} value={text('connectionId')} onchange={(e)=>chooseConnection(e.currentTarget.value)}><option value="">Choose connection</option>{#each connections.filter(c=>c.state==='ENABLED') as connection}<option value={connection.id}>{connection.name} · {connection.connectorKey}</option>{/each}</select></label>
{/if}
{#if node.kind==='database_source' || node.kind==='database_target'}
  <div class="inline"><label>Schema<input disabled={readonly} value={text('schema')} oninput={(e)=>set('schema',e.currentTarget.value)}/></label><button disabled={busy||!text('connectionId')} onclick={loadSchemas}>Discover</button></div>{#if schemas.length}<div class="chips">{#each schemas as value}<button onclick={()=>{set('schema',value);void loadDatasets()}}>{value}</button>{/each}</div>{/if}
  <div class="inline"><label>{node.kind==='database_target'?'Target table':'Table or view'}<input disabled={readonly} value={text(node.kind==='database_target'?'table':'dataset')} oninput={(e)=>set(node.kind==='database_target'?'table':'dataset',e.currentTarget.value)}/></label>{#if node.kind==='database_source'}<button disabled={busy||!text('schema')} onclick={loadDatasets}>Browse</button>{/if}</div>
  {#if datasets.length}<div class="chips">{#each datasets as value}<button onclick={()=>set('dataset',value.name)}>{value.name}<small>{value.type}</small></button>{/each}</div>{/if}
{/if}
{#if node.kind==='sql_query_source'}<label>Read-only SQL<textarea disabled={readonly} value={text('query')} oninput={(e)=>set('query',e.currentTarget.value)} placeholder="SELECT …"></textarea></label>{/if}
{#if node.kind==='database_source'}<div class="actions"><Button variant="secondary" disabled={busy||!text('dataset')} onclick={loadSchema}>Refresh schema</Button><Button variant="secondary" disabled={busy||!text('dataset')} onclick={loadPreview}>Preview 50 rows</Button></div>{/if}
{#if node.kind==='database_target'}<label>Write mode<select disabled={readonly} value={text('writeMode')||'APPEND'} onchange={(e)=>set('writeMode',e.currentTarget.value)}><option>APPEND</option><option>TRUNCATE_AND_LOAD</option><option>UPSERT</option></select></label>{#if text('writeMode')==='UPSERT'}<label>Key columns (JSON)<textarea disabled={readonly} value={json('keyColumns')} onblur={(e)=>setJson('keyColumns',e.currentTarget.value)}></textarea></label>{/if}<label>Column mappings (JSON)<textarea disabled={readonly} value={json('mappings')} onblur={(e)=>setJson('mappings',e.currentTarget.value)}></textarea></label>{/if}
{#if node.kind==='select_columns'}<label>Selected columns in order (JSON)<textarea disabled={readonly} value={json('columns')} onblur={(e)=>setJson('columns',e.currentTarget.value)}></textarea></label>
{:else if node.kind==='rename_columns'}<label>Rename mappings (JSON)<textarea disabled={readonly} value={json('mappings')} onblur={(e)=>setJson('mappings',e.currentTarget.value)}></textarea></label>
{:else if node.kind==='filter'}<label>Predicate group (JSON)<textarea disabled={readonly} value={json('predicate')} onblur={(e)=>setJson('predicate',e.currentTarget.value)}></textarea></label>
{:else if node.kind==='derived_column'}<label>New column<input disabled={readonly} value={text('column')} oninput={(e)=>set('column',e.currentTarget.value)}/></label><label>Safe expression<textarea disabled={readonly} value={text('expression')} oninput={(e)=>set('expression',e.currentTarget.value)}></textarea></label><label>Output type<select disabled={readonly} value={text('outputType')||'string'} onchange={(e)=>set('outputType',e.currentTarget.value)}>{#each ['string','integer','decimal','boolean','date','timestamp'] as type}<option>{type}</option>{/each}</select></label>
{:else if node.kind==='cast'}<label>Conversions (JSON)<textarea disabled={readonly} value={json('casts')} onblur={(e)=>setJson('casts',e.currentTarget.value)}></textarea></label>
{:else if node.kind==='aggregate'}<label>Group by columns (JSON)<textarea disabled={readonly} value={json('groupBy')} onblur={(e)=>setJson('groupBy',e.currentTarget.value)}></textarea></label><label>Aggregates (JSON)<textarea disabled={readonly} value={json('aggregates')} onblur={(e)=>setJson('aggregates',e.currentTarget.value)}></textarea></label>
{:else if node.kind==='join'}<label>Join type<select disabled={readonly} value={text('joinType')||'INNER'} onchange={(e)=>set('joinType',e.currentTarget.value)}>{#each ['INNER','LEFT','RIGHT','FULL'] as type}<option>{type}</option>{/each}</select></label><label>Join key mappings (JSON)<textarea disabled={readonly} value={json('keys')} onblur={(e)=>setJson('keys',e.currentTarget.value)}></textarea></label>
{:else if ['lookup','union','split_router','null_handling','deduplicate','data_quality','validation_gate','sort'].includes(node.kind)}<label>Configuration (JSON)<textarea class="large" disabled={readonly} value={JSON.stringify(config,null,2)} onblur={(e)=>{try{onchange(JSON.parse(e.currentTarget.value));message=''}catch{message='Configuration must contain valid JSON.'}}}></textarea></label>
{:else if node.kind==='limit_sample'}<label>Row limit<input type="number" min="1" disabled={readonly} value={number('limit',100)} oninput={(e)=>set('limit',Number(e.currentTarget.value))}/></label>{/if}
{#if message}<p class="message" role="alert">{message}</p>{/if}
{#if node.outputSchema.length}<p class="section-label">Output schema</p><div class="schema">{#each node.outputSchema as field}<div><strong>{field.name}</strong><span>{field.logicalType}{field.nullable?' · nullable':''}</span></div>{/each}</div>{/if}
{#if preview.length}<p class="section-label">Preview</p><div class="preview"><table><thead><tr>{#each Object.keys(preview[0]) as column}<th>{column}</th>{/each}</tr></thead><tbody>{#each preview as row}<tr>{#each Object.keys(preview[0]) as column}<td>{String(row[column]??'')}</td>{/each}</tr>{/each}</tbody></table></div>{/if}

<style>.section-label{margin:.9rem 0 .45rem;color:var(--text-muted);font-size:.58rem;font-weight:750;letter-spacing:.1em;text-transform:uppercase}label{display:grid;min-width:0;gap:.28rem;margin-bottom:.7rem;color:var(--text-muted);font-size:.64rem;font-weight:650}input,select,textarea{width:100%;min-width:0;border:1px solid var(--border-default);border-radius:6px;background:#fff;padding:.48rem;color:var(--text-primary);font:inherit;font-size:.68rem}input,select{height:2.15rem}textarea{min-height:4.6rem;resize:vertical;font-family:var(--font-mono)}textarea.large{min-height:10rem}.inline{display:grid;grid-template-columns:1fr auto;align-items:end;gap:.4rem}.inline>button,.chips button{border:1px solid var(--border-default);border-radius:6px;background:#fff;padding:.45rem;font-size:.62rem;cursor:pointer}.inline>button{height:2.15rem;margin-bottom:.7rem}.chips{display:flex;max-height:6rem;flex-wrap:wrap;gap:.25rem;overflow:auto;margin:-.35rem 0 .7rem}.chips button{padding:.25rem .4rem}.chips small{display:block;color:var(--text-muted);font-size:.5rem}.actions{display:flex;gap:.35rem;margin-bottom:.7rem}.message{color:var(--danger);font-size:.64rem}.schema{border:1px solid var(--border-default);border-radius:6px;background:#fff}.schema div{display:flex;justify-content:space-between;gap:.5rem;border-bottom:1px solid var(--border-subtle);padding:.38rem .45rem;font-size:.6rem}.schema div:last-child{border:0}.schema span{color:var(--text-muted)}.preview{overflow:auto;max-height:12rem;border:1px solid var(--border-default);background:#fff}.preview table{border-collapse:collapse;font-size:.56rem}.preview th,.preview td{padding:.3rem;border:1px solid var(--border-subtle);white-space:nowrap}</style>
