<script lang="ts">
  import type { ConnectionDefinition,PipelineDesignEdge,PipelineDesignNode,PipelineDesignValidationResult,SchemaField } from '$lib/api/pipelines'; import Icon from '$lib/components/ui/Icon.svelte'; import ConnectionEditor from './ConnectionEditor.svelte'; import ValidationPanel from './ValidationPanel.svelte'; import NodeConfiguration from './NodeConfiguration.svelte';
  let {node,selectedEdge,nodes,edges,pipelineName,pipelineState,connections,revision,readonly,validation,onLabel,onConfiguration,onConnector,onSchema,onDeleteNode,onDeleteEdge,onDeleteEdgeById,onConnect,onSelectNode}:{node:PipelineDesignNode|null;selectedEdge:PipelineDesignEdge|null;nodes:PipelineDesignNode[];edges:PipelineDesignEdge[];pipelineName:string;pipelineState:string;connections:ConnectionDefinition[];revision:number;readonly:boolean;validation:PipelineDesignValidationResult|null;onLabel:(value:string)=>void;onConfiguration:(value:Record<string,unknown>)=>void;onConnector:(value:string|null)=>void;onSchema:(value:SchemaField[])=>void;onDeleteNode:()=>void;onDeleteEdge:()=>void;onDeleteEdgeById:(id:string)=>void;onConnect:(source:string,target:string)=>void;onSelectNode:(id:string)=>void}=$props();
  const labelFor=(id:string)=>nodes.find(n=>n.id===id)?.label??id;
</script>
<aside class="inspector" aria-label="Pipeline inspector"><header><p class="eyebrow">{node?'Node inspector':selectedEdge?'Connection':'Pipeline inspector'}</p></header>
{#if node}<div class="inspector-body"><div class="node-heading"><span class="node-icon"><Icon name={node.type==='SOURCE'?'database':node.type==='TARGET'?'target':'transform'} size={17}/></span><div><strong>{node.label}</strong><small>{node.kind.replaceAll('_',' ')} · {node.type}</small></div></div><p class="section-label">General</p><label>Label<input value={node.label} disabled={readonly} oninput={(e)=>onLabel(e.currentTarget.value)}/></label><NodeConfiguration {node} {connections} {readonly} onchange={onConfiguration} onconnector={onConnector} onschema={onSchema}/><p class="section-label">Identity</p><div class="property"><span>Node ID</span><code>{node.id}</code></div>{#if !readonly}<div class="danger-zone"><button onclick={onDeleteNode}><Icon name="trash" size={14}/>Delete node</button></div>{/if}</div>
{:else if selectedEdge}<div class="inspector-body"><div class="edge-summary"><span>{labelFor(selectedEdge.sourceNodeId)}<small>{selectedEdge.sourcePort}</small></span><b>→</b><span>{labelFor(selectedEdge.targetNodeId)}<small>{selectedEdge.targetPort}</small></span></div><div class="property"><span>Connection ID</span><code>{selectedEdge.id}</code></div>{#if !readonly}<div class="danger-zone"><button onclick={onDeleteEdge}><Icon name="trash" size={14}/>Delete connection</button></div>{/if}</div>
{:else}<div class="summary"><p class="section-label">Pipeline</p><h2>{pipelineName}</h2><p>Select a node to configure it, or a connection to inspect it.</p><dl><div><dt>State</dt><dd>{pipelineState}</dd></div><div><dt>Revision</dt><dd>{revision}</dd></div><div><dt>Nodes</dt><dd>{nodes.length}</dd></div><div><dt>Connections</dt><dd>{edges.length}</dd></div></dl></div>{/if}
<ValidationPanel result={validation} onselect={onSelectNode}/><ConnectionEditor {nodes} {edges} {readonly} onconnect={onConnect} ondelete={onDeleteEdgeById}/></aside>
<style>.inspector{height:100%;min-height:0;overflow:auto;border-left:1px solid var(--border-default);background:var(--bg-sidebar)}.inspector>header{padding:1.05rem 1rem .65rem}.inspector-body{padding:0 1rem 1rem}.node-heading{display:flex;align-items:center;gap:.65rem;margin-bottom:1rem;padding-bottom:.85rem;border-bottom:1px solid var(--border-default)}.node-icon{display:grid;width:2rem;height:2rem;place-items:center;border-radius:6px;background:var(--accent-soft);color:var(--accent)}.node-heading strong{display:block;font-size:.78rem}.node-heading small,.edge-summary small{display:block;color:var(--text-muted);font-size:.55rem;text-transform:capitalize}.section-label{margin:.9rem 0 .45rem;color:var(--text-muted);font-size:.58rem;font-weight:750;letter-spacing:.1em;text-transform:uppercase}label{display:grid;gap:.28rem;margin-bottom:.75rem;color:var(--text-muted);font-size:.66rem;font-weight:650}input{height:2.15rem;border:1px solid var(--border-default);border-radius:var(--radius-sm);background:#fff;padding:0 .5rem;font-size:.72rem}.property{display:grid;gap:.25rem}.property span{color:var(--text-muted);font-size:.62rem}.property code{overflow-wrap:anywhere;font-family:var(--font-mono);font-size:.6rem}.danger-zone{margin-top:1.2rem;padding-top:.8rem;border-top:1px solid var(--border-default)}.danger-zone button{display:flex;align-items:center;gap:.4rem;border:0;background:transparent;color:var(--danger);font-size:.68rem;font-weight:650;cursor:pointer}.summary{padding:0 1rem}.summary h2{margin:0 0 .35rem;font-size:.86rem}.summary>p:not(.section-label){color:var(--text-muted);font-size:.7rem}.summary dl{margin:0;border-top:1px solid var(--border-default)}.summary dl div{display:flex;justify-content:space-between;border-bottom:1px solid var(--border-default);padding:.55rem 0}.summary dt{color:var(--text-muted);font-size:.66rem}.summary dd{margin:0;font-size:.7rem;font-weight:650}.edge-summary{display:grid;grid-template-columns:1fr auto 1fr;align-items:center;gap:.4rem;border:1px solid var(--border-default);border-radius:var(--radius-md);background:#fff;padding:.7rem;font-size:.67rem;text-align:center}.edge-summary b{color:var(--accent)}</style>
