<script lang="ts">
  import type { ConnectorDefinition, PipelineDesignEdge, PipelineDesignNode } from '$lib/api/pipelines'; import Icon from '$lib/components/ui/Icon.svelte'; import ConnectionEditor from './ConnectionEditor.svelte'; import ValidationPanel from './ValidationPanel.svelte'; import type { PipelineDesignValidationResult } from '$lib/api/pipelines';
  let { node, selectedEdge, nodes, edgeCount, connectors, revision, readonly, validation, onLabel, onConnector, onDeleteNode, onDeleteEdge, onConnect, onSelectNode }: { node: PipelineDesignNode | null; selectedEdge: PipelineDesignEdge | null; nodes: PipelineDesignNode[]; edgeCount: number; connectors: ConnectorDefinition[]; revision: number; readonly: boolean; validation: PipelineDesignValidationResult | null; onLabel: (value:string)=>void; onConnector:(value:string)=>void; onDeleteNode:()=>void; onDeleteEdge:()=>void; onConnect:(source:string,target:string)=>void; onSelectNode:(id:string)=>void }=$props();
  const labelFor=(id:string)=>nodes.find(n=>n.id===id)?.label??id;
</script>
<aside class="inspector" aria-label="Pipeline inspector"><header><p class="eyebrow">{node?'Node inspector':selectedEdge?'Connection':'Pipeline inspector'}</p></header>
{#if node}<div class="inspector-body"><div class="node-heading"><span class="node-icon"><Icon name={node.type==='SOURCE'?'database':node.type==='TARGET'?'target':'transform'} size={17}/></span><div><strong>{node.label}</strong><small>{node.type}</small></div></div><label>Label<input value={node.label} disabled={readonly} oninput={(e)=>onLabel(e.currentTarget.value)}/></label>{#if node.type!=='TRANSFORM'}<label>Connector<select value={node.connectorKey??''} disabled={readonly} onchange={(e)=>onConnector(e.currentTarget.value)}>{#each connectors as connector}<option value={connector.key}>{connector.displayName}</option>{/each}</select></label>{/if}<div class="property"><span>Node ID</span><code>{node.id}</code></div>{#if !readonly}<div class="danger-zone"><button onclick={onDeleteNode}><Icon name="trash" size={14}/>Delete node</button></div>{/if}</div>
{:else if selectedEdge}<div class="inspector-body"><div class="edge-summary"><span>{labelFor(selectedEdge.sourceNodeId)}</span><b>→</b><span>{labelFor(selectedEdge.targetNodeId)}</span></div><div class="property"><span>Connection ID</span><code>{selectedEdge.id}</code></div>{#if !readonly}<div class="danger-zone"><button onclick={onDeleteEdge}><Icon name="trash" size={14}/>Delete connection</button></div>{/if}</div>
{:else}<div class="summary"><p>Select a node to configure it, or a connection to inspect it.</p><dl><div><dt>Nodes</dt><dd>{nodes.length}</dd></div><div><dt>Connections</dt><dd>{edgeCount}</dd></div><div><dt>Revision</dt><dd>{revision}</dd></div></dl></div>{/if}
<ValidationPanel result={validation} onselect={onSelectNode}/><ConnectionEditor {nodes} {readonly} onconnect={onConnect}/></aside>
<style>.inspector{height:100%;overflow:auto;border-left:1px solid var(--border-default);background:var(--bg-sidebar)}.inspector>header{padding:1.2rem 1rem .8rem}.inspector-body{padding:0 1rem 1rem}.node-heading{display:flex;align-items:center;gap:.65rem;margin-bottom:1rem;padding-bottom:.85rem;border-bottom:1px solid var(--border-default)}.node-icon{display:grid;width:2rem;height:2rem;place-items:center;border-radius:6px;background:var(--accent-soft);color:var(--accent)}.node-heading strong{display:block;font-size:.78rem}.node-heading small{display:block;color:var(--text-muted);font-size:.58rem;font-weight:700;letter-spacing:.09em}label{display:grid;gap:.28rem;margin-bottom:.75rem;color:var(--text-muted);font-size:.66rem;font-weight:650}input,select{min-width:0;height:2.15rem;border:1px solid var(--border-default);border-radius:var(--radius-sm);background:#fff;padding:0 .5rem;color:var(--text-primary);font-size:.72rem}.property{display:grid;gap:.25rem;margin-top:.9rem}.property span{color:var(--text-muted);font-size:.62rem;font-weight:650}.property code{overflow-wrap:anywhere;color:var(--text-secondary);font-family:var(--font-mono);font-size:.6rem}.danger-zone{margin-top:1.2rem;padding-top:.8rem;border-top:1px solid var(--border-default)}.danger-zone button{display:flex;align-items:center;gap:.4rem;border:0;background:transparent;color:var(--danger);padding:.2rem 0;font-size:.68rem;font-weight:650;cursor:pointer}.summary{padding:0 1rem}.summary>p{margin:0 0 1rem;color:var(--text-muted);font-size:.7rem}.summary dl{margin:0;border-top:1px solid var(--border-default)}.summary dl div{display:flex;justify-content:space-between;border-bottom:1px solid var(--border-default);padding:.55rem 0}.summary dt{color:var(--text-muted);font-size:.66rem}.summary dd{margin:0;color:var(--text-primary);font-size:.7rem;font-weight:650}.edge-summary{display:grid;grid-template-columns:1fr auto 1fr;align-items:center;gap:.4rem;border:1px solid var(--border-default);border-radius:var(--radius-md);background:#fff;padding:.7rem;font-size:.67rem;text-align:center}.edge-summary b{color:var(--accent)}</style>
