<script lang="ts">
  import Icon from '$lib/components/ui/Icon.svelte'; import type { NodeTypeDefinition,PipelineDesignNodeType } from '$lib/api/pipelines';
  let { readonly, nodeTypes, onadd }: { readonly:boolean;nodeTypes:NodeTypeDefinition[];onadd:(kind:string)=>void }=$props();
  let search=$state('');const categories:PipelineDesignNodeType[]=['SOURCE','TRANSFORM','GOVERNANCE','TARGET'];
  let filtered=$derived(nodeTypes.filter(item=>!search||`${item.displayName} ${item.description}`.toLowerCase().includes(search.toLowerCase())));
  function drag(event:DragEvent,kind:string){if(readonly)return;event.dataTransfer?.setData('application/x-nexetl-node-kind',kind);if(event.dataTransfer)event.dataTransfer.effectAllowed='copy'}
</script>
<aside class="palette" aria-label="Node palette"><header><p class="eyebrow">Node palette</p><p>Drag a node onto the canvas or click to add.</p><input aria-label="Search node types" placeholder="Search nodes" bind:value={search}/></header>
  {#each categories as category}{#if filtered.some(item=>item.category===category)}<section><h2>{category}</h2>{#each filtered.filter(item=>item.category===category) as item}<button disabled={readonly} draggable={!readonly} ondragstart={(event)=>drag(event,item.key)} onclick={()=>onadd(item.key)} title={item.description}><span class="palette-icon {category.toLowerCase()}"><Icon name={category==='SOURCE'?'database':category==='TARGET'?'target':'transform'} size={17}/></span><span><strong>{item.displayName}</strong><small>{item.description}</small></span><Icon name="plus" size={14}/></button>{/each}</section>{/if}{/each}
  {#if readonly}<p class="readonly-note">This archived design is read only.</p>{/if}
</aside>
<style>.palette{height:100%;overflow:auto;border-right:1px solid var(--border-default);background:var(--bg-sidebar);padding:1rem}.palette header{padding:.2rem .2rem 1rem}.palette header p:last-of-type{margin:.3rem 0 .7rem;color:var(--text-muted);font-size:.68rem}.palette input{width:100%;border:1px solid var(--border-default);border-radius:6px;background:#fff;padding:.45rem .55rem;font:inherit;font-size:.68rem}.palette section{margin-bottom:1rem}.palette h2{margin:0 0 .4rem .2rem;color:var(--text-muted);font-size:.56rem;letter-spacing:.1em}.palette button{display:grid;width:100%;grid-template-columns:1.8rem 1fr auto;align-items:center;gap:.45rem;margin-bottom:.35rem;border:1px solid var(--border-default);border-radius:8px;background:var(--bg-surface);padding:.52rem;text-align:left;box-shadow:var(--shadow-sm);cursor:grab}.palette button:hover:not(:disabled){border-color:#aeb9c7;box-shadow:0 3px 10px rgb(20 31 50 / 8%)}.palette button:disabled{cursor:not-allowed;opacity:.58}.palette-icon{display:grid;width:1.7rem;height:1.7rem;place-items:center;border-radius:6px;background:#f2effb;color:var(--node-transform)}.palette-icon.source{background:#e8f5fa;color:var(--node-source)}.palette-icon.target{background:#e9f6f1;color:var(--node-target)}.palette strong{display:block;font-size:.69rem}.palette small{display:-webkit-box;margin-top:.06rem;overflow:hidden;color:var(--text-muted);font-size:.57rem;-webkit-box-orient:vertical;-webkit-line-clamp:2;line-clamp:2}.readonly-note{border-top:1px solid var(--border-default);padding-top:1rem;color:var(--text-muted);font-size:.7rem}</style>
