<script lang="ts">
  import Icon from '$lib/components/ui/Icon.svelte'; import type { PipelineDesignNodeType } from '$lib/api/pipelines';
  let { readonly, onadd }: { readonly: boolean; onadd: (type: PipelineDesignNodeType) => void } = $props();
  const items=[{type:'SOURCE' as const,title:'Source',description:'Select a connector',icon:'database'},{type:'TRANSFORM' as const,title:'Transform',description:'Shape or transform data',icon:'transform'},{type:'TARGET' as const,title:'Target',description:'Write to a destination',icon:'target'}];
</script>
<aside class="palette" aria-label="Node palette">
  <header><p class="eyebrow">Node palette</p><p>Add nodes to the Pipeline canvas.</p></header>
  {#each items as item}<section><h2>{item.type}</h2><button disabled={readonly} onclick={()=>onadd(item.type)}><span class="palette-icon {item.type.toLowerCase()}"><Icon name={item.icon} size={18}/></span><span><strong>{item.title}</strong><small>{item.description}</small></span><Icon name="plus" size={15}/></button></section>{/each}
  {#if readonly}<p class="readonly-note">This archived design is read only.</p>{/if}
</aside>
<style>.palette{height:100%;overflow:auto;border-right:1px solid var(--border-default);background:var(--bg-sidebar);padding:1rem}.palette header{padding:.2rem .2rem 1.1rem}.palette header p:last-child{margin:.3rem 0 0;color:var(--text-muted);font-size:.72rem}.palette section{margin-bottom:1rem}.palette h2{margin:0 0 .4rem .2rem;color:var(--text-muted);font-size:.59rem;letter-spacing:.1em}.palette button{display:grid;width:100%;grid-template-columns:2rem 1fr auto;align-items:center;gap:.5rem;border:1px solid var(--border-default);border-radius:var(--radius-md);background:var(--bg-surface);padding:.62rem;text-align:left;box-shadow:var(--shadow-sm);cursor:pointer}.palette button:hover:not(:disabled){border-color:#aeb9c7;box-shadow:0 3px 10px rgb(20 31 50 / 8%);transform:translateY(-1px)}.palette button:disabled{cursor:not-allowed;opacity:.58}.palette-icon{display:grid;width:1.85rem;height:1.85rem;place-items:center;border-radius:6px;background:#f2effb;color:var(--node-transform)}.palette-icon.source{background:#e8f5fa;color:var(--node-source)}.palette-icon.target{background:#e9f6f1;color:var(--node-target)}.palette strong{display:block;font-size:.75rem}.palette small{display:block;margin-top:.08rem;color:var(--text-muted);font-size:.63rem}.readonly-note{border-top:1px solid var(--border-default);padding-top:1rem;color:var(--text-muted);font-size:.7rem}</style>
