<script lang="ts">
  import Icon from '$lib/components/ui/Icon.svelte';
  import type { PipelineDesignNode } from '$lib/api/pipelines';
  let { node, selected, readonly, onselect, ondragstart }: { node: PipelineDesignNode; selected: boolean; readonly: boolean; onselect: () => void; ondragstart: (event: PointerEvent) => void } = $props();
  const icon = $derived(node.type === 'SOURCE' ? 'database' : node.type === 'TARGET' ? 'target' : 'transform');
</script>
<button class:selected class:readonly class="pipeline-node {node.type.toLowerCase()}" style={`left:${node.positionX}px;top:${node.positionY}px`} aria-label={`${node.label}, ${node.type.toLowerCase()} node`} aria-pressed={selected} onclick={onselect} onpointerdown={ondragstart}>
  {#if node.type !== 'SOURCE'}<span class="port input-port" aria-hidden="true"></span>{/if}
  <span class="node-icon"><Icon name={icon} size={17}/></span>
  <span class="identity"><strong>{node.label}</strong><small>{node.type}</small></span>
  {#if node.type !== 'TRANSFORM'}<span class="connector">{node.connectorKey ?? 'No connector'}</span>{/if}
  {#if node.type !== 'TARGET'}<span class="port output-port" aria-hidden="true"></span>{/if}
</button>
<style>.pipeline-node{position:absolute;display:grid;grid-template-columns:2rem 1fr;width:208px;min-height:76px;align-items:center;border:1px solid var(--border-strong);border-top:3px solid var(--node-transform);border-radius:var(--radius-md);background:var(--bg-surface);padding:.7rem .75rem .55rem;box-shadow:0 3px 10px rgb(20 31 50 / 8%);text-align:left;cursor:grab;user-select:none}.pipeline-node:active{cursor:grabbing}.pipeline-node:hover{border-color:#9da9b8;box-shadow:0 6px 18px rgb(20 31 50 / 12%)}.pipeline-node.selected{border-color:var(--accent);box-shadow:0 0 0 2px rgb(49 87 213 / 15%),0 8px 20px rgb(20 31 50 / 12%)}.pipeline-node.source{border-top-color:var(--node-source)}.pipeline-node.target{border-top-color:var(--node-target)}.pipeline-node.readonly{cursor:pointer}.node-icon{display:grid;width:1.75rem;height:1.75rem;place-items:center;border-radius:6px;background:#f2effb;color:var(--node-transform)}.source .node-icon{background:#e8f5fa;color:var(--node-source)}.target .node-icon{background:#e9f6f1;color:var(--node-target)}.identity{display:block;min-width:0;padding-left:.2rem}.identity strong{display:block;overflow:hidden;color:var(--text-primary);font-size:.78rem;font-weight:650;text-overflow:ellipsis;white-space:nowrap}.identity small{display:block;margin-top:.12rem;color:var(--text-muted);font-size:.57rem;font-weight:750;letter-spacing:.1em}.connector{grid-column:1/-1;margin:.55rem -.75rem -.55rem;padding:.38rem .75rem;border-top:1px solid var(--border-subtle);color:var(--text-muted);font-family:var(--font-mono);font-size:.62rem}.port{position:absolute;top:50%;width:11px;height:11px;border:2px solid #fff;border-radius:50%;background:#8a96a7;box-shadow:0 0 0 1px #8a96a7}.input-port{left:-6px}.output-port{right:-6px}.source .port{background:var(--node-source);box-shadow:0 0 0 1px var(--node-source)}.target .port{background:var(--node-target);box-shadow:0 0 0 1px var(--node-target)}</style>
