<script lang="ts">
  import Icon from '$lib/components/ui/Icon.svelte'; import StatusBadge from '$lib/components/ui/StatusBadge.svelte'; import type { PipelineDefinition } from '$lib/api/pipelines';
  let { pipeline,revision,status,saving,running=false,canUndo=false,canRedo=false,onfit,onvalidate,onsave,onrun,onundo,onredo,onarrange,onduplicate }: {pipeline:PipelineDefinition;revision:number;status:'saved'|'dirty'|'error'|'conflict';saving:boolean;running?:boolean;canUndo?:boolean;canRedo?:boolean;onfit:()=>void;onvalidate:()=>void;onsave:()=>void;onrun:()=>void;onundo:()=>void;onredo:()=>void;onarrange:()=>void;onduplicate:()=>void}=$props();
</script>
<header class="designer-header">
  <div class="identity"><a href={`/pipelines/${pipeline.id}`} aria-label="Back to Pipeline"><Icon name="arrow-left" size={17}/></a><div><h1>{pipeline.name}</h1><div class="meta"><StatusBadge state={pipeline.state}/>{#if pipeline.state==='ARCHIVED'}<span class="readonly">Read only</span>{/if}<span>Revision {revision}</span><span class="save-status {status}"><i></i>{saving?'Saving…':status==='dirty'?'Unsaved changes':status==='conflict'?'Revision conflict':status==='error'?'Save failed':'Saved'}</span></div></div></div>
  <div class="actions"><button class="tool" disabled={!canUndo} onclick={onundo} title="Undo (Ctrl+Z)">Undo</button><button class="tool" disabled={!canRedo} onclick={onredo} title="Redo (Ctrl+Shift+Z)">Redo</button><button class="tool" onclick={onduplicate}>Duplicate</button><button class="tool" onclick={onarrange}>Arrange</button><button class="tool" onclick={onfit}><Icon name="fit" size={15}/>Fit</button><button class="tool" onclick={onvalidate}><Icon name="check" size={15}/>Validate</button>{#if pipeline.state!=='ARCHIVED'}<button class="save" disabled={saving||status==='saved'} onclick={onsave}><Icon name="save" size={15}/>{saving?'Saving…':'Save'}</button><button class="run" disabled={saving||running} onclick={onrun}>{running?'Queuing…':'Run pipeline'}</button>{/if}</div>
</header>
<style>.designer-header{display:flex;min-height:4.55rem;align-items:center;justify-content:space-between;gap:1rem;border-bottom:1px solid var(--border-default);background:var(--bg-surface);padding:.55rem 1.1rem}.identity{display:flex;min-width:0;align-items:center;gap:.75rem}.identity>a{display:grid;width:2rem;height:2rem;flex:none;place-items:center;border:1px solid var(--border-default);border-radius:var(--radius-sm);color:var(--text-secondary)}h1{overflow:hidden;max-width:28rem;margin:0;color:var(--text-primary);font-size:.98rem;font-weight:680;text-overflow:ellipsis;white-space:nowrap}.meta{display:flex;align-items:center;gap:.55rem;margin-top:.3rem;color:var(--text-muted);font-size:.62rem}.readonly{color:var(--warning);font-weight:650}.save-status{display:flex;align-items:center;gap:.3rem}.save-status i{width:.42rem;height:.42rem;border-radius:50%;background:var(--success)}.save-status.dirty i{background:var(--warning)}.save-status.error i,.save-status.conflict i{background:var(--danger)}.actions{display:flex;flex-wrap:wrap;justify-content:flex-end;gap:.35rem}.actions button{display:flex;height:2.05rem;align-items:center;gap:.35rem;border:1px solid var(--border-default);border-radius:var(--radius-sm);background:#fff;padding:0 .55rem;font-size:.66rem;font-weight:650;cursor:pointer}.actions button:hover:not(:disabled){border-color:var(--border-strong);background:var(--bg-subtle)}.actions .save{border-color:var(--accent);background:var(--accent);color:#fff}.actions .run{border-color:#176f52;background:#176f52;color:#fff}.actions button:disabled{opacity:.45;cursor:not-allowed}@media(max-width:1050px){.actions .tool:nth-child(-n+4){display:none}}@media(max-width:700px){.designer-header{height:auto}.tool{display:none!important}.meta>span:nth-last-child(2){display:none}}</style>
