# Generated by Django 6.1.1 on 2026-09-28 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PipelineDefinitionRecord',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'nexetl_pipeline_definition',
            },
        ),
    ]
