# Generated by Django 6.1.1 on 2026-09-30 01:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipelines', '0004_pipeline_design'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConnectionSecretRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider_key', models.CharField(default='local_encrypted', max_length=32)),
                ('encrypted_value', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'nexetl_connection_secret',
            },
        ),
        migrations.AlterModelOptions(
            name='pipelinedefinitionrecord',
            options={'permissions': (('register_pipeline_definition', 'Can register pipeline definition'), ('inspect_pipeline_definition', 'Can inspect pipeline definition'), ('list_pipeline_definition', 'Can list pipeline definitions'), ('update_pipeline_definition', 'Can update pipeline definitions'), ('archive_pipeline_definition', 'Can archive pipeline definitions'), ('design_pipeline_definition', 'Can design pipeline definitions'), ('publish_pipeline_version', 'Can publish pipeline versions'), ('run_pipeline_definition', 'Can run pipeline definitions'), ('inspect_pipeline_run', 'Can inspect pipeline runs'), ('cancel_pipeline_run', 'Can cancel pipeline runs'), ('manage_pipeline_schedule', 'Can manage pipeline schedules'))},
        ),
        migrations.AddField(
            model_name='pipelinedesignedgerecord',
            name='source_port',
            field=models.CharField(default='output', max_length=64),
        ),
        migrations.AddField(
            model_name='pipelinedesignedgerecord',
            name='target_port',
            field=models.CharField(default='input', max_length=64),
        ),
        migrations.AddField(
            model_name='pipelinedesignnoderecord',
            name='configuration',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='pipelinedesignnoderecord',
            name='configuration_version',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='pipelinedesignnoderecord',
            name='input_schema',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='pipelinedesignnoderecord',
            name='kind',
            field=models.CharField(default='legacy', max_length=64),
        ),
        migrations.AddField(
            model_name='pipelinedesignnoderecord',
            name='output_schema',
            field=models.JSONField(default=list),
        ),
        migrations.CreateModel(
            name='ConnectionRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=120)),
                ('connector_key', models.CharField(db_index=True, max_length=64)),
                ('description', models.TextField(blank=True, default='')),
                ('configuration', models.JSONField(default=dict)),
                ('state', models.CharField(db_index=True, default='ENABLED', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('secret', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='connections', to='pipelines.connectionsecretrecord')),
            ],
            options={
                'db_table': 'nexetl_connection',
                'permissions': (('list_connection', 'Can list connections'), ('create_connection', 'Can create connections'), ('inspect_connection', 'Can inspect connections'), ('update_connection', 'Can update connections'), ('test_connection', 'Can test connections')),
            },
        ),
        migrations.CreateModel(
            name='PipelineRunRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(db_index=True, default='QUEUED', max_length=16)),
                ('trigger_type', models.CharField(db_index=True, default='MANUAL', max_length=16)),
                ('idempotency_key', models.CharField(blank=True, max_length=128, null=True)),
                ('scheduled_for', models.DateTimeField(blank=True, null=True)),
                ('queued_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('claimed_by', models.CharField(blank=True, max_length=160, null=True)),
                ('claimed_at', models.DateTimeField(blank=True, null=True)),
                ('heartbeat_at', models.DateTimeField(blank=True, null=True)),
                ('lease_expires_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('current_node_id', models.UUIDField(blank=True, null=True)),
                ('cancellation_requested', models.BooleanField(default=False)),
                ('error_code', models.CharField(blank=True, max_length=80, null=True)),
                ('error_message', models.TextField(blank=True, default='')),
                ('metrics', models.JSONField(default=dict)),
                ('attempt', models.PositiveSmallIntegerField(default=1)),
                ('initiated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pipeline_runs', to=settings.AUTH_USER_MODEL)),
                ('parent_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retry_runs', to='pipelines.pipelinerunrecord')),
                ('pipeline', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='runs', to='pipelines.pipelinedefinitionrecord')),
            ],
            options={
                'db_table': 'nexetl_pipeline_run',
                'ordering': ['-queued_at'],
            },
        ),
        migrations.CreateModel(
            name='PipelineRunEventRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_id', models.UUIDField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('level', models.CharField(default='INFO', max_length=12)),
                ('event', models.CharField(max_length=80)),
                ('message', models.CharField(max_length=500)),
                ('context', models.JSONField(default=dict)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='pipelines.pipelinerunrecord')),
            ],
            options={
                'db_table': 'nexetl_pipeline_run_event',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='PipelineScheduleRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('enabled', models.BooleanField(db_index=True, default=True)),
                ('expression', models.CharField(max_length=120)),
                ('timezone', models.CharField(default='UTC', max_length=64)),
                ('next_run_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pipeline_schedules', to=settings.AUTH_USER_MODEL)),
                ('pipeline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='pipelines.pipelinedefinitionrecord')),
            ],
            options={
                'db_table': 'nexetl_pipeline_schedule',
            },
        ),
        migrations.AddField(
            model_name='pipelinerunrecord',
            name='schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='runs', to='pipelines.pipelineschedulerecord'),
        ),
        migrations.CreateModel(
            name='PipelineVersionRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version', models.PositiveIntegerField()),
                ('design_revision', models.PositiveIntegerField()),
                ('snapshot', models.JSONField()),
                ('snapshot_hash', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pipeline_versions', to=settings.AUTH_USER_MODEL)),
                ('pipeline', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='versions', to='pipelines.pipelinedefinitionrecord')),
            ],
            options={
                'db_table': 'nexetl_pipeline_version',
                'ordering': ['-version'],
            },
        ),
        migrations.CreateModel(
            name='PipelineVersionNodeRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('design_node_id', models.UUIDField()),
                ('kind', models.CharField(max_length=64)),
                ('category', models.CharField(max_length=16)),
                ('label', models.CharField(max_length=120)),
                ('configuration_version', models.PositiveSmallIntegerField(default=1)),
                ('configuration', models.JSONField(default=dict)),
                ('input_schema', models.JSONField(default=list)),
                ('output_schema', models.JSONField(default=list)),
                ('position_x', models.FloatField()),
                ('position_y', models.FloatField()),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='pipelines.pipelineversionrecord')),
            ],
            options={
                'db_table': 'nexetl_pipeline_version_node',
            },
        ),
        migrations.CreateModel(
            name='PipelineVersionEdgeRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('design_edge_id', models.UUIDField()),
                ('source_node_id', models.UUIDField()),
                ('source_port', models.CharField(default='output', max_length=64)),
                ('target_node_id', models.UUIDField()),
                ('target_port', models.CharField(default='input', max_length=64)),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edges', to='pipelines.pipelineversionrecord')),
            ],
            options={
                'db_table': 'nexetl_pipeline_version_edge',
            },
        ),
        migrations.AddField(
            model_name='pipelinerunrecord',
            name='version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='runs', to='pipelines.pipelineversionrecord'),
        ),
        migrations.CreateModel(
            name='PipelineNodeRunRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('node_id', models.UUIDField()),
                ('label', models.CharField(max_length=120)),
                ('kind', models.CharField(max_length=64)),
                ('status', models.CharField(db_index=True, default='QUEUED', max_length=16)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('input_rows', models.BigIntegerField(default=0)),
                ('output_rows', models.BigIntegerField(default=0)),
                ('rejected_rows', models.BigIntegerField(default=0)),
                ('batch_count', models.PositiveIntegerField(default=0)),
                ('error_code', models.CharField(blank=True, max_length=80, null=True)),
                ('error_message', models.TextField(blank=True, default='')),
                ('metrics', models.JSONField(default=dict)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='node_runs', to='pipelines.pipelinerunrecord')),
            ],
            options={
                'db_table': 'nexetl_pipeline_node_run',
                'constraints': [models.UniqueConstraint(fields=('run', 'node_id'), name='nexetl_run_node')],
            },
        ),
        migrations.AddConstraint(
            model_name='pipelineschedulerecord',
            constraint=models.UniqueConstraint(fields=('pipeline', 'name'), name='nexetl_schedule_name'),
        ),
        migrations.AddConstraint(
            model_name='pipelineversionrecord',
            constraint=models.UniqueConstraint(fields=('pipeline', 'version'), name='nexetl_pipeline_version_number'),
        ),
        migrations.AddConstraint(
            model_name='pipelineversionnoderecord',
            constraint=models.UniqueConstraint(fields=('version', 'design_node_id'), name='nexetl_version_design_node'),
        ),
        migrations.AddIndex(
            model_name='pipelinerunrecord',
            index=models.Index(fields=['status', 'queued_at'], name='nexetl_run_claim_idx'),
        ),
        migrations.AddConstraint(
            model_name='pipelinerunrecord',
            constraint=models.UniqueConstraint(condition=models.Q(('idempotency_key__isnull', False)), fields=('pipeline', 'idempotency_key'), name='nexetl_run_idempotency'),
        ),
        migrations.AddConstraint(
            model_name='pipelinerunrecord',
            constraint=models.UniqueConstraint(condition=models.Q(('schedule__isnull', False)), fields=('schedule', 'scheduled_for'), name='nexetl_schedule_occurrence'),
        ),
    ]
