# Generated by Django 6.1.1 on 2026-09-30 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipelines', '0005_connectionsecretrecord_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='pipelinedesignedgerecord',
            name='nexetl_design_unique_edge',
        ),
        migrations.AddConstraint(
            model_name='pipelinedesignedgerecord',
            constraint=models.UniqueConstraint(fields=('design', 'source_node', 'source_port', 'target_node', 'target_port'), name='nexetl_design_unique_edge'),
        ),
    ]
