<script lang="ts">
  import { onMount } from 'svelte'; import { session } from '$lib/session'; import PageHeader from '$lib/components/ui/PageHeader.svelte';
  let collapsed=$state(false); onMount(()=>collapsed=localStorage.getItem('nexetl.sidebar.collapsed')==='true');
  function update(){localStorage.setItem('nexetl.sidebar.collapsed',String(collapsed));window.dispatchEvent(new CustomEvent('nexetl-sidebar-preference'))}
</script>
<svelte:head><title>Settings | NEXETL</title></svelte:head>
<PageHeader title="Settings" description="Workspace preferences and environment information."/>
<div class="settings"><section><div><p class="eyebrow">Interface</p><h2>Navigation</h2><p>Choose how the workspace navigation opens on this device.</p></div><label class="switch-row"><span><strong>Prefer collapsed navigation</strong><small>Use a compact icon-only sidebar on larger screens.</small></span><input type="checkbox" bind:checked={collapsed} onchange={update}/></label></section><section><div><p class="eyebrow">Session</p><h2>Signed-in account</h2></div><dl><div><dt>Username</dt><dd>{$session.username}</dd></div><div><dt>Access</dt><dd>Super Admin</dd></div></dl></section><section><div><p class="eyebrow">Environment</p><h2>Current workspace</h2></div><dl><div><dt>Environment</dt><dd><span class="environment">Local development</span></dd></div><div><dt>Application</dt><dd>NEXETL</dd></div></dl></section></div>
<style>.settings{display:grid;max-width:52rem;border:1px solid var(--border-default);border-radius:var(--radius-md);background:#fff;box-shadow:var(--shadow-sm);overflow:hidden}.settings section{display:grid;grid-template-columns:14rem 1fr;gap:2rem;padding:1.2rem;border-bottom:1px solid var(--border-default)}.settings section:last-child{border:0}h2{margin:.28rem 0 0;font-size:.86rem}.settings section>div>p:last-child{margin:.3rem 0 0;color:var(--text-muted);font-size:.66rem}.switch-row{display:flex;align-items:center;justify-content:space-between;gap:1rem;border:1px solid var(--border-default);border-radius:var(--radius-md);background:var(--bg-subtle);padding:.7rem .8rem}.switch-row strong,.switch-row small{display:block}.switch-row strong{font-size:.7rem}.switch-row small{margin-top:.15rem;color:var(--text-muted);font-size:.62rem}.switch-row input{width:2rem;height:1rem;accent-color:var(--accent)}dl{margin:0}dl div{display:flex;justify-content:space-between;border-bottom:1px solid var(--border-subtle);padding:.45rem 0}dl div:last-child{border:0}dt{color:var(--text-muted);font-size:.66rem}dd{margin:0;color:var(--text-secondary);font-size:.7rem;font-weight:600}.environment{display:inline-flex;align-items:center;gap:.4rem}.environment::before{width:.4rem;height:.4rem;border-radius:50%;background:var(--success);content:""}@media(max-width:650px){.settings section{grid-template-columns:1fr;gap:.8rem}}</style>
