<script lang="ts">
  import {goto}from '$app/navigation';import {page}from '$app/state';import {archivePipelineDefinition,getPipelineDefinition,listPipelineVersions,pipelineErrorMessage,publishPipelineVersion,updatePipelineDefinition,type NexetlError,type PipelineDefinition,type PipelineVersion}from '$lib/api/pipelines';import {formatTimestamp}from '$lib/format';import PipelineWorkspaceNav from '$lib/components/PipelineWorkspaceNav.svelte';import PageHeader from '$lib/components/ui/PageHeader.svelte';import Button from '$lib/components/ui/Button.svelte';import Alert from '$lib/components/ui/Alert.svelte';
  let item=$state<PipelineDefinition|null>(null),versions=$state<PipelineVersion[]>([]),name=$state(''),description=$state(''),pending=$state(false),error=$state(''),notice=$state('');$effect(()=>{if(page.params.pipelineDefinitionId)void load(page.params.pipelineDefinitionId)});
  async function load(id:string){try{[item,{items:versions}]=await Promise.all([getPipelineDefinition(id),listPipelineVersions(id)]);name=item.name;description=item.description}catch(e){error=pipelineErrorMessage(e as NexetlError)}}
  async function save(){if(!item)return;pending=true;try{item=await updatePipelineDefinition(item.id,name,description);notice='Pipeline settings saved.'}catch(e){error=pipelineErrorMessage(e as NexetlError)}finally{pending=false}}
  async function publish(){if(!item)return;pending=true;try{const version=await publishPipelineVersion(item.id);notice=`Version ${version.version} is ready to run.`;await load(item.id)}catch(e){error=pipelineErrorMessage(e as NexetlError)}finally{pending=false}}
  async function archive(){if(!item||!confirm('Archive this Pipeline? It will become read only.'))return;pending=true;try{await archivePipelineDefinition(item.id);await goto(`/pipelines/${item.id}`)}catch(e){error=pipelineErrorMessage(e as NexetlError)}finally{pending=false}}
</script>
<svelte:head><title>Pipeline Settings | NEXETL</title></svelte:head>{#if item}<PageHeader title={item.name} description="Pipeline identity, immutable versions and lifecycle settings."/><PipelineWorkspaceNav pipelineId={item.id}/>{#if error}<Alert variant="error">{error}</Alert>{/if}{#if notice}<Alert variant="success">{notice}</Alert>{/if}<div class="grid"><form onsubmit={(e)=>{e.preventDefault();void save()}}><h2>Identity</h2><label>Name<input bind:value={name} maxlength="120" required/></label><label>Description<textarea bind:value={description} maxlength="1000"></textarea></label><div class="actions"><Button type="submit" loading={pending} disabled={item.state==='ARCHIVED'}>Save settings</Button>{#if item.state!=='ARCHIVED'}<Button type="button" variant="danger" disabled={pending} onclick={archive}>Archive Pipeline</Button>{/if}</div></form><section><header><div><h2>Version history</h2><p>Immutable executable snapshots created by Run or explicit publish.</p></div><Button variant="secondary" disabled={item.state==='ARCHIVED'} loading={pending} onclick={publish}>Publish version</Button></header>{#each versions as version}<article><strong>Version {version.version}</strong><span>Design revision {version.designRevision}</span><time>{formatTimestamp(version.createdAt)}</time></article>{:else}<p class="empty">No executable versions have been published.</p>{/each}</section></div>{/if}
<style>.grid{display:grid;grid-template-columns:minmax(20rem,.8fr) 1fr;gap:1rem}form,section{border:1px solid var(--border-default);border-radius:var(--radius-lg);background:#fff;padding:1rem}h2{margin:0 0 .8rem;font-size:.9rem}label{display:grid;gap:.3rem;margin-bottom:.8rem;color:var(--text-secondary);font-size:.7rem;font-weight:650}input,textarea{border:1px solid var(--border-default);border-radius:6px;padding:.55rem;font:inherit}textarea{min-height:7rem}.actions,section header{display:flex;align-items:center;justify-content:space-between;gap:.7rem}section header p{margin:-.5rem 0 .8rem;color:var(--text-muted);font-size:.65rem}article{display:grid;grid-template-columns:1fr auto auto;gap:1rem;border-top:1px solid var(--border-subtle);padding:.65rem 0;font-size:.68rem}article span,article time{color:var(--text-muted)}.empty{color:var(--text-muted);font-size:.7rem}@media(max-width:850px){.grid{grid-template-columns:1fr}}</style>
