<script lang="ts">
  import { goto } from '$app/navigation'; import { pipelineErrorMessage, registerPipelineDefinition, type NexetlError } from '$lib/api/pipelines';
  import PageHeader from '$lib/components/ui/PageHeader.svelte'; import Button from '$lib/components/ui/Button.svelte'; import Alert from '$lib/components/ui/Alert.svelte';
  let name = $state(''), description = $state(''), pending = $state(false), error = $state(''), nameError = $state(''), descriptionError = $state('');
  function validate() { nameError = !name.trim() ? 'Pipeline name is required.' : name.trim().length > 120 ? 'Pipeline name must be at most 120 characters.' : ''; descriptionError = description.length > 1000 ? 'Description must be at most 1000 characters.' : ''; return !nameError && !descriptionError; }
  async function submit() { if (!validate()) return; pending = true; error = ''; try { const definition = await registerPipelineDefinition(name.trim(), description.trim()); await goto(`/pipelines/${definition.id}/design`); } catch (failure) { error = pipelineErrorMessage(failure as NexetlError); } finally { pending = false; } }
</script>
<svelte:head><title>New Pipeline | NEXETL</title></svelte:head>
<PageHeader title="New Pipeline" description="Create a Pipeline Definition to begin authoring a data flow." />
<form onsubmit={(event) => { event.preventDefault(); void submit(); }} novalidate><label for="name">Pipeline name <span aria-hidden="true">*</span></label><input id="name" bind:value={name} maxlength="120" autocomplete="off" aria-invalid={Boolean(nameError)} aria-describedby="name-help" onblur={validate}/><small id="name-help">{name.length}/120{nameError ? ` — ${nameError}` : ''}</small><label for="description">Description</label><textarea id="description" bind:value={description} maxlength="1000" aria-invalid={Boolean(descriptionError)} aria-describedby="description-help" onblur={validate}></textarea><small id="description-help">{description.length}/1000{descriptionError ? ` — ${descriptionError}` : ''}</small>{#if error}<Alert variant="error">{error}</Alert>{/if}<div class="actions"><Button variant="secondary" onclick={() => goto('/pipelines')}>Cancel</Button><Button type="submit" loading={pending}>Create pipeline</Button></div></form>
<style>form{display:grid;gap:var(--space-2);max-width:42rem;border-top:1px solid var(--border-default);padding-top:var(--space-5)}label{margin-top:var(--space-3);font-weight:600}input,textarea{width:100%;border:1px solid var(--border-default);border-radius:var(--radius-sm);padding:.6rem;font:inherit}textarea{min-height:8rem;resize:vertical}small{color:var(--text-muted)}.actions{display:flex;justify-content:flex-end;gap:var(--space-2);margin-top:var(--space-4)}</style>
