<script lang="ts">
  import { untrack } from 'svelte'; import Button from '$lib/components/ui/Button.svelte'; import type { ConnectionDefinition } from '$lib/api/pipelines';
  let {initial=null,pending=false,onsubmit,ontest}:{initial?:ConnectionDefinition|null;pending?:boolean;onsubmit:(value:{name:string;connectorKey:string;description:string;configuration:Record<string,unknown>;password:string})=>void;ontest?:()=>void}=$props();
  const seed=untrack(()=>initial);
  let name=$state(seed?.name??''),connectorKey=$state(seed?.connectorKey??'postgresql'),description=$state(seed?.description??''),host=$state(String(seed?.configuration.host??'localhost')),port=$state(Number(seed?.configuration.port??5432)),database=$state(String(seed?.configuration.database??'')),username=$state(String(seed?.configuration.username??'')),password=$state(''),sslMode=$state(String(seed?.configuration.sslMode??'prefer')),driver=$state(String(seed?.configuration.driver??'ODBC Driver 18 for SQL Server')),previousConnector=$state(seed?.connectorKey??'postgresql');
  $effect(()=>{if(connectorKey!==previousConnector){port=connectorKey==='postgresql'?5432:connectorKey==='sqlserver'?1433:3306;previousConnector=connectorKey}});
  function submit(){const configuration:Record<string,unknown>={host,port,database,username};if(connectorKey==='postgresql'||connectorKey==='mysql'||connectorKey==='mariadb')configuration.sslMode=sslMode;if(connectorKey==='sqlserver'){configuration.driver=driver;configuration.encrypt='yes';configuration.trustServerCertificate='no'}onsubmit({name,connectorKey,description,configuration,password})}
</script>
<form onsubmit={(event)=>{event.preventDefault();submit()}}><div class="grid"><label>Connection name<input bind:value={name} maxlength="120" required/></label><label>Database type<select bind:value={connectorKey} disabled={Boolean(initial)}><option value="postgresql">PostgreSQL</option><option value="sqlserver">SQL Server</option><option value="mysql">MySQL</option><option value="mariadb">MariaDB</option></select></label><label class="wide">Description<textarea bind:value={description} maxlength="1000"></textarea></label><label>Host<input bind:value={host} required/></label><label>Port<input type="number" min="1" max="65535" bind:value={port} required/></label><label>Database<input bind:value={database} required/></label><label>Username<input autocomplete="username" bind:value={username} required/></label><label>Password {initial?.secretConfigured?'(leave blank to keep current)':''}<input type="password" autocomplete="new-password" bind:value={password} required={!initial}/></label>{#if connectorKey==='sqlserver'}<label>ODBC driver<input bind:value={driver}/></label>{:else}<label>SSL mode<select bind:value={sslMode}><option>prefer</option><option>require</option><option>verify-ca</option><option>verify-full</option><option>disable</option></select></label>{/if}</div><div class="actions"><Button type="submit" loading={pending}>{initial?'Save connection':'Create connection'}</Button>{#if ontest}<Button type="button" variant="secondary" disabled={pending} onclick={ontest}>Test connection</Button>{/if}</div><p class="security">The password is write-only. It is encrypted through the configured secret provider and is never returned by the API.</p></form>
<style>form{max-width:52rem;border:1px solid var(--border-default);border-radius:var(--radius-lg);background:#fff;padding:1.2rem;box-shadow:var(--shadow-sm)}.grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:.8rem}.wide{grid-column:1/-1}label{display:grid;gap:.32rem;color:var(--text-secondary);font-size:.7rem;font-weight:650}input,select,textarea{border:1px solid var(--border-default);border-radius:var(--radius-sm);padding:.55rem;font:inherit;font-size:.75rem}input,select{height:2.35rem}textarea{min-height:4.5rem}.actions{display:flex;gap:.5rem;margin-top:1rem}.security{margin:1rem 0 0;color:var(--text-muted);font-size:.65rem}@media(max-width:650px){.grid{grid-template-columns:1fr}.wide{grid-column:auto}}</style>
