<script lang="ts">
  import { goto } from '$app/navigation'; import { onMount } from 'svelte';
  import { listConnectors, listPipelineDefinitions, pipelineErrorMessage, type NexetlError, type PipelineDefinition } from '$lib/api/pipelines'; import { formatTimestamp } from '$lib/format';
  import PageHeader from '$lib/components/ui/PageHeader.svelte'; import Button from '$lib/components/ui/Button.svelte'; import Alert from '$lib/components/ui/Alert.svelte'; import StatusBadge from '$lib/components/ui/StatusBadge.svelte';
  let loading = $state(true), error = $state(''), total = $state(0), drafts = $state(0), archived = $state(0), connectors = $state(0), recent = $state<PipelineDefinition[]>([]);
  onMount(async () => { try { const [all, draft, old, catalogue, latest] = await Promise.all([listPipelineDefinitions({ pageSize: 1 }), listPipelineDefinitions({ pageSize: 1, state: 'DRAFT' }), listPipelineDefinitions({ pageSize: 1, state: 'ARCHIVED' }), listConnectors(), listPipelineDefinitions({ pageSize: 5, sort: '-updatedAt' })]); total = all.totalItems; drafts = draft.totalItems; archived = old.totalItems; connectors = catalogue.items.filter((item) => item.availability === 'AVAILABLE').length; recent = latest.items; } catch (failure) { error = pipelineErrorMessage(failure as NexetlError); } finally { loading = false; } });
</script>
<svelte:head><title>Home | NEXETL</title></svelte:head>
<PageHeader title="Home" description="Pipeline authoring workspace."><Button onclick={() => goto('/pipelines/new')}>＋ New pipeline</Button></PageHeader>
{#if loading}<p role="status">Loading workspace…</p>{:else if error}<Alert variant="error">{error}</Alert>{:else}
  <section class="metrics" aria-label="Workspace summary"><div><span>Total pipelines</span><strong>{total}</strong></div><div><span>Draft</span><strong>{drafts}</strong></div><div><span>Archived</span><strong>{archived}</strong></div><div><span>Connectors</span><strong>{connectors}</strong></div></section>
  <section class="recent"><div class="section-heading"><p class="eyebrow">Recent pipelines</p><a href="/pipelines">View all</a></div>{#if recent.length}<div class="recent-list">{#each recent as item}<a href={`/pipelines/${item.id}`}><span><strong>{item.name}</strong><small>{item.description || 'No description'}</small></span><span class="recent-meta"><StatusBadge state={item.state} /><time>{formatTimestamp(item.updatedAt)}</time></span></a>{/each}</div>{:else}<div class="empty"><h2>No pipelines yet</h2><p>Create your first Pipeline Definition to begin building a data flow.</p><Button onclick={() => goto('/pipelines/new')}>Create pipeline</Button></div>{/if}</section>
{/if}
<style>.metrics{display:grid;grid-template-columns:repeat(4,1fr);border:1px solid var(--border-default);border-radius:var(--radius-md);background:var(--bg-surface);box-shadow:var(--shadow-sm)}.metrics div{padding:1rem 1.2rem;border-right:1px solid var(--border-default)}.metrics div:last-child{border:0}.metrics span,small{display:block;color:var(--text-muted);font-size:.68rem}.metrics strong{display:block;margin-top:.25rem;font-size:1.45rem;font-weight:650}.recent{margin-top:var(--space-7);max-width:64rem}.section-heading{display:flex;justify-content:space-between;align-items:center;margin-bottom:.6rem}.section-heading a{font-size:.72rem;font-weight:600}.recent-list{border:1px solid var(--border-default);border-radius:var(--radius-md);background:#fff;overflow:hidden}.recent-list a{display:flex;justify-content:space-between;align-items:center;border-bottom:1px solid var(--border-subtle);padding:.8rem 1rem;color:var(--text-primary)}.recent-list a:last-child{border:0}.recent-list a:hover{background:var(--bg-subtle)}.recent-list strong{display:block;font-size:.78rem}.recent-list small{margin-top:.15rem}.recent-meta{display:flex;align-items:center;gap:1rem}.recent-meta time{min-width:9rem;color:var(--text-muted);font-size:.66rem;text-align:right}.empty{border:1px dashed var(--border-strong);border-radius:var(--radius-md);background:#fff;padding:var(--space-6);text-align:center}.empty h2{font-size:.95rem}.empty p{color:var(--text-secondary);font-size:.78rem}@media(max-width:720px){.metrics{grid-template-columns:repeat(2,1fr)}.metrics div:nth-child(2){border-right:0}.metrics div:nth-child(-n+2){border-bottom:1px solid var(--border-default)}.recent-meta time{display:none}}</style>
