<script lang="ts">
  import { goto } from '$app/navigation'; import { onMount } from 'svelte';
  import { listConnectors, listPipelineDefinitions, pipelineErrorMessage, type NexetlError, type PipelineDefinition } from '$lib/api/pipelines'; import { formatTimestamp } from '$lib/format';
  import PageHeader from '$lib/components/ui/PageHeader.svelte'; import Button from '$lib/components/ui/Button.svelte'; import Alert from '$lib/components/ui/Alert.svelte'; import StatusBadge from '$lib/components/ui/StatusBadge.svelte';
  let loading = $state(true), error = $state(''), total = $state(0), drafts = $state(0), archived = $state(0), connectors = $state(0), recent = $state<PipelineDefinition[]>([]);
  onMount(async () => { try { const [all, draft, old, catalogue, latest] = await Promise.all([listPipelineDefinitions({ pageSize: 1 }), listPipelineDefinitions({ pageSize: 1, state: 'DRAFT' }), listPipelineDefinitions({ pageSize: 1, state: 'ARCHIVED' }), listConnectors(), listPipelineDefinitions({ pageSize: 5, sort: '-updatedAt' })]); total = all.totalItems; drafts = draft.totalItems; archived = old.totalItems; connectors = catalogue.items.filter((item) => item.availability === 'AVAILABLE').length; recent = latest.items; } catch (failure) { error = pipelineErrorMessage(failure as NexetlError); } finally { loading = false; } });
</script>
<svelte:head><title>Home | NEXETL</title></svelte:head>
<PageHeader title="Home" description="Overview of your Pipeline authoring workspace."><Button onclick={() => goto('/pipelines/new')}>New pipeline</Button></PageHeader>
{#if loading}<p role="status">Loading workspace…</p>{:else if error}<Alert variant="error">{error}</Alert>{:else}
  <section class="metrics" aria-label="Workspace summary"><div><span>Total pipelines</span><strong>{total}</strong></div><div><span>Draft pipelines</span><strong>{drafts}</strong></div><div><span>Archived pipelines</span><strong>{archived}</strong></div><div><span>Available connectors</span><strong>{connectors}</strong></div></section>
  <section class="recent"><div class="section-heading"><h2>Recently updated</h2><a href="/pipelines">View all pipelines</a></div>{#if recent.length}<div class="recent-list">{#each recent as item}<a href={`/pipelines/${item.id}`}><span><strong>{item.name}</strong><small>{formatTimestamp(item.updatedAt)}</small></span><StatusBadge state={item.state} /></a>{/each}</div>{:else}<div class="empty"><h2>No pipelines yet</h2><p>Create your first Pipeline Definition to begin building a data flow.</p><Button onclick={() => goto('/pipelines/new')}>Create pipeline</Button></div>{/if}</section>
{/if}
<style>.metrics{display:grid;grid-template-columns:repeat(4,1fr);border-block:1px solid var(--border-default)}.metrics div{padding:var(--space-4);border-right:1px solid var(--border-default)}.metrics div:last-child{border:0}.metrics span,small{display:block;color:var(--text-muted);font-size:.78rem}.metrics strong{display:block;margin-top:.25rem;font-size:1.7rem}.recent{margin-top:var(--space-7);max-width:54rem}.section-heading{display:flex;justify-content:space-between;align-items:baseline}.section-heading h2{font-size:1rem}.recent-list{border-top:1px solid var(--border-default)}.recent-list a{display:flex;justify-content:space-between;align-items:center;border-bottom:1px solid var(--border-default);padding:var(--space-3) 0;color:var(--text-primary)}.recent-list a:hover{text-decoration:none;color:var(--accent)}.empty{border-block:1px solid var(--border-default);padding:var(--space-6) 0}.empty h2{font-size:1.1rem}.empty p{color:var(--text-secondary)}@media(max-width:720px){.metrics{grid-template-columns:repeat(2,1fr)}.metrics div:nth-child(2){border-right:0}.metrics div:nth-child(-n+2){border-bottom:1px solid var(--border-default)}}</style>
