<script lang="ts">
  import { goto } from '$app/navigation'; import { page } from '$app/state'; import { onMount } from 'svelte';
  import { archivePipelineDefinition, listPipelineDefinitions, pipelineErrorMessage, type NexetlError, type PipelineListResponse, type PipelineState } from '$lib/api/pipelines'; import { formatTimestamp } from '$lib/format';
  import PageHeader from '$lib/components/ui/PageHeader.svelte'; import Button from '$lib/components/ui/Button.svelte'; import Alert from '$lib/components/ui/Alert.svelte'; import StatusBadge from '$lib/components/ui/StatusBadge.svelte'; import ConfirmDialog from '$lib/components/ui/ConfirmDialog.svelte';
  const sortOptions = [{ value: '-updatedAt', label: 'Recently updated' }, { value: 'updatedAt', label: 'Oldest updated' }, { value: '-createdAt', label: 'Newest created' }, { value: 'createdAt', label: 'Oldest created' }, { value: 'name', label: 'Name A–Z' }, { value: '-name', label: 'Name Z–A' }] as const;
  let loading = $state(true), error = $state(''), data = $state<PipelineListResponse | null>(null), archiveId = $state<string | null>(null), archiving = $state(false);
  function query() { const u = page.url; return { search: u.searchParams.get('search') ?? '', state: (u.searchParams.get('state') ?? '') as PipelineState | '', sort: u.searchParams.get('sort') ?? '-updatedAt', page: Number(u.searchParams.get('page') ?? 1) }; }
  async function load() { loading = true; error = ''; const q = query(); try { data = await listPipelineDefinitions({ ...q, state: q.state || undefined, pageSize: 20, sort: q.sort as typeof sortOptions[number]['value'] }); } catch (failure) { error = pipelineErrorMessage(failure as NexetlError); } finally { loading = false; } }
  onMount(load); $effect(() => { page.url.search; if (!loading) void load(); });
  function update(values: Record<string, string>) { const p = new URLSearchParams(page.url.searchParams); for (const [key, value] of Object.entries(values)) value ? p.set(key, value) : p.delete(key); if (!('page' in values)) p.set('page', '1'); void goto(`/pipelines?${p}`); }
  async function archive() { if (!archiveId) return; archiving = true; try { await archivePipelineDefinition(archiveId); archiveId = null; await load(); } catch (failure) { error = pipelineErrorMessage(failure as NexetlError); } finally { archiving = false; } }
</script>
<svelte:head><title>Pipelines | NEXETL</title></svelte:head>
<PageHeader title="Pipelines" description="Create, find and manage Pipeline Definitions."><Button onclick={() => goto('/pipelines/new')}>New pipeline</Button></PageHeader>
<div class="toolbar"><label>Search <input value={query().search} oninput={(event) => update({ search: event.currentTarget.value })} placeholder="Find pipelines" /></label><label>State <select value={query().state} onchange={(event) => update({ state: event.currentTarget.value })}><option value="">All</option><option value="DRAFT">Draft</option><option value="ARCHIVED">Archived</option></select></label><label>Sort <select value={query().sort} onchange={(event) => update({ sort: event.currentTarget.value })}>{#each sortOptions as option}<option value={option.value}>{option.label}</option>{/each}</select></label></div>
{#if error}<Alert variant="error">{error}</Alert>{/if}{#if loading}<p role="status">Loading pipelines…</p>{:else if data?.items.length}<div class="table-wrap"><table><thead><tr><th>Name</th><th>State</th><th>Updated</th><th>Created</th><th>ID</th><th>Actions</th></tr></thead><tbody>{#each data.items as item}<tr><td><a href={`/pipelines/${item.id}`}>{item.name}</a></td><td><StatusBadge state={item.state}/></td><td>{formatTimestamp(item.updatedAt)}</td><td>{formatTimestamp(item.createdAt)}</td><td><code>{item.id}</code></td><td><a href={`/pipelines/${item.id}`}>Open</a>{#if item.state === 'DRAFT'} <button class="link" onclick={() => archiveId = item.id}>Archive</button>{/if}</td></tr>{/each}</tbody></table></div>{#if data.totalPages > 0}<div class="pagination"><Button variant="secondary" disabled={data.page <= 1} onclick={() => update({ page: String(data!.page - 1) })}>Previous</Button><span>Page {data.page} of {data.totalPages}</span><Button variant="secondary" disabled={data.page >= data.totalPages} onclick={() => update({ page: String(data!.page + 1) })}>Next</Button></div>{/if}{:else if data?.totalItems === 0 && !query().search && !query().state}<section class="empty"><h2>No pipelines yet</h2><p>Create your first Pipeline Definition to begin building a data flow.</p><Button onclick={() => goto('/pipelines/new')}>Create pipeline</Button></section>{:else}<section class="empty"><h2>No matching pipelines</h2><p>Try changing your search or filters.</p><Button variant="secondary" onclick={() => goto('/pipelines')}>Clear filters</Button></section>{/if}
<ConfirmDialog open={archiveId !== null} title="Archive Pipeline?" message="Archived Pipeline Definitions remain available for inspection but cannot be edited." pending={archiving} onconfirm={archive} oncancel={() => archiveId = null}/>
<style>.toolbar{display:flex;gap:var(--space-3);margin-bottom:var(--space-5)}label{display:grid;gap:.25rem;color:var(--text-muted);font-size:.78rem}input,select{min-height:2.25rem;border:1px solid var(--border-default);border-radius:var(--radius-sm);background:#fff;padding:.35rem .5rem;color:var(--text-primary)}.table-wrap{overflow:auto;border-top:1px solid var(--border-default)}table{width:100%;border-collapse:collapse;font-size:.85rem}th,td{padding:.75rem .5rem;border-bottom:1px solid var(--border-default);text-align:left}th{color:var(--text-muted);font-size:.72rem;text-transform:uppercase}code{font-size:.72rem;color:var(--text-muted)}.link{border:0;background:transparent;color:var(--danger);cursor:pointer}.pagination{display:flex;align-items:center;justify-content:flex-end;gap:var(--space-3);margin-top:var(--space-4)}.empty{border-block:1px solid var(--border-default);padding:var(--space-6) 0}.empty p{color:var(--text-secondary)}@media(max-width:700px){.toolbar{flex-wrap:wrap}.table-wrap{overflow:visible}thead{display:none}table,tbody,tr,td{display:block}tr{border-bottom:1px solid var(--border-default);padding:var(--space-3) 0}td{border:0;padding:.18rem 0}td:before{content:attr(data-label);color:var(--text-muted)}td:nth-child(3),td:nth-child(4),td:nth-child(5){display:none}}</style>
