<script lang="ts">
  import { goto } from '$app/navigation'; import { page } from '$app/state';
  import { archivePipelineDefinition, listPipelineDefinitions, pipelineErrorMessage, type NexetlError, type PipelineListResponse, type PipelineState } from '$lib/api/pipelines'; import { formatTimestamp } from '$lib/format';
  import PageHeader from '$lib/components/ui/PageHeader.svelte'; import Button from '$lib/components/ui/Button.svelte'; import Alert from '$lib/components/ui/Alert.svelte'; import StatusBadge from '$lib/components/ui/StatusBadge.svelte'; import ConfirmDialog from '$lib/components/ui/ConfirmDialog.svelte'; import Icon from '$lib/components/ui/Icon.svelte';
  const sortOptions = [{ value: '-updatedAt', label: 'Recently updated' }, { value: 'updatedAt', label: 'Oldest updated' }, { value: '-createdAt', label: 'Newest created' }, { value: 'createdAt', label: 'Oldest created' }, { value: 'name', label: 'Name A–Z' }, { value: '-name', label: 'Name Z–A' }] as const;
  let loading = $state(true), error = $state(''), data = $state<PipelineListResponse | null>(null), archiveId = $state<string | null>(null), archiving = $state(false);
  function query() { const u = page.url; return { search: u.searchParams.get('search') ?? '', state: (u.searchParams.get('state') ?? '') as PipelineState | '', sort: u.searchParams.get('sort') ?? '-updatedAt', page: Number(u.searchParams.get('page') ?? 1) }; }
  async function load() { loading = true; error = ''; const q = query(); try { data = await listPipelineDefinitions({ ...q, state: q.state || undefined, pageSize: 20, sort: q.sort as typeof sortOptions[number]['value'] }); } catch (failure) { error = pipelineErrorMessage(failure as NexetlError); } finally { loading = false; } }
  $effect(() => { page.url.search; void load(); });
  function update(values: Record<string, string>) { const p = new URLSearchParams(page.url.searchParams); for (const [key, value] of Object.entries(values)) value ? p.set(key, value) : p.delete(key); if (!('page' in values)) p.set('page', '1'); void goto(`/pipelines?${p}`); }
  async function archive() { if (!archiveId) return; archiving = true; try { await archivePipelineDefinition(archiveId); archiveId = null; await load(); } catch (failure) { error = pipelineErrorMessage(failure as NexetlError); } finally { archiving = false; } }
</script>
<svelte:head><title>Pipelines | NEXETL</title></svelte:head>
<PageHeader title="Pipelines" description="Manage and author Pipeline Definitions."><Button onclick={() => goto('/pipelines/new')}>＋ New pipeline</Button></PageHeader>
<div class="toolbar"><label class="search"><span class="sr">Search pipelines</span><Icon name="search" size={15}/><input value={query().search} oninput={(event) => update({ search: event.currentTarget.value })} placeholder="Search pipelines…" /></label><label><span>State</span><select value={query().state} onchange={(event) => update({ state: event.currentTarget.value })}><option value="">All states</option><option value="DRAFT">Draft</option><option value="ARCHIVED">Archived</option></select></label><label><span>Sort</span><select value={query().sort} onchange={(event) => update({ sort: event.currentTarget.value })}>{#each sortOptions as option}<option value={option.value}>{option.label}</option>{/each}</select></label>{#if data}<span class="result-count">{data.totalItems} {data.totalItems===1?'pipeline':'pipelines'}</span>{/if}</div>
{#if error}<Alert variant="error">{error}</Alert>{/if}{#if loading}<p role="status">Loading pipelines…</p>{:else if data?.items.length}<div class="table-wrap"><table><thead><tr><th>Pipeline</th><th>State</th><th>Updated</th><th>Created</th><th>ID</th><th><span class="sr">Actions</span></th></tr></thead><tbody>{#each data.items as item}<tr><td><a class="pipeline-name" href={`/pipelines/${item.id}`}><strong>{item.name}</strong><small>{item.description||'No description'}</small></a></td><td><StatusBadge state={item.state}/></td><td>{formatTimestamp(item.updatedAt)}</td><td>{formatTimestamp(item.createdAt)}</td><td><code>{item.id}</code></td><td><div class="row-actions"><a href={`/pipelines/${item.id}`}>Open</a><a href={`/pipelines/${item.id}/design`}>{item.state==='DRAFT'?'Design':'View'}</a>{#if item.state === 'DRAFT'}<button onclick={() => archiveId = item.id}>Archive</button>{/if}</div></td></tr>{/each}</tbody></table></div>{#if data.totalPages > 1}<div class="pagination"><Button variant="secondary" disabled={data.page <= 1} onclick={() => update({ page: String(data!.page - 1) })}>Previous</Button><span>Page {data.page} of {data.totalPages}</span><Button variant="secondary" disabled={data.page >= data.totalPages} onclick={() => update({ page: String(data!.page + 1) })}>Next</Button></div>{/if}{:else if data?.totalItems === 0 && !query().search && !query().state}<section class="empty"><h2>No pipelines yet</h2><p>Create your first Pipeline Definition to begin building a data flow.</p><Button onclick={() => goto('/pipelines/new')}>Create pipeline</Button></section>{:else}<section class="empty"><h2>No matching pipelines</h2><p>Try changing your search or filters.</p><Button variant="secondary" onclick={() => goto('/pipelines')}>Clear filters</Button></section>{/if}
<ConfirmDialog open={archiveId !== null} title="Archive Pipeline?" message="Archived Pipeline Definitions remain available for inspection but cannot be edited." pending={archiving} onconfirm={archive} oncancel={() => archiveId = null}/>
<style>.sr{position:absolute;width:1px;height:1px;overflow:hidden;clip:rect(0,0,0,0)}.toolbar{display:flex;align-items:end;gap:.65rem;margin-bottom:1rem}.toolbar label{display:grid;gap:.25rem;color:var(--text-muted);font-size:.63rem;font-weight:650}.toolbar select,.toolbar input{height:2.25rem;border:1px solid var(--border-default);border-radius:var(--radius-sm);background:#fff;padding:0 .6rem;color:var(--text-primary);font-size:.72rem}.search{position:relative;display:block!important;flex:1;max-width:26rem}.search :global(svg){position:absolute;left:.65rem;top:.62rem;color:var(--text-muted)}.search input{width:100%;padding-left:2rem}.result-count{margin-left:auto;padding-bottom:.48rem;color:var(--text-muted);font-size:.66rem}.table-wrap{overflow:auto;border:1px solid var(--border-default);border-radius:var(--radius-md);background:#fff;box-shadow:var(--shadow-sm)}table{width:100%;border-collapse:collapse;font-size:.72rem}th,td{padding:.72rem .8rem;border-bottom:1px solid var(--border-subtle);text-align:left;vertical-align:middle}tbody tr:last-child td{border-bottom:0}tbody tr:hover{background:#fafbfd}th{background:#f8fafc;color:var(--text-muted);font-size:.59rem;letter-spacing:.08em;text-transform:uppercase}.pipeline-name{display:block;min-width:13rem;color:var(--text-primary)}.pipeline-name strong{display:block;font-size:.76rem}.pipeline-name small{display:block;max-width:26rem;margin-top:.12rem;overflow:hidden;color:var(--text-muted);font-size:.64rem;text-overflow:ellipsis;white-space:nowrap}code{color:var(--text-muted);font-family:var(--font-mono);font-size:.61rem}.row-actions{display:flex;align-items:center;justify-content:flex-end;gap:.65rem;white-space:nowrap}.row-actions a,.row-actions button{border:0;background:transparent;color:var(--text-secondary);padding:0;font-size:.66rem;font-weight:600;cursor:pointer}.row-actions a:hover{color:var(--accent)}.row-actions button:hover{color:var(--danger)}.pagination{display:flex;align-items:center;justify-content:flex-end;gap:var(--space-3);margin-top:var(--space-4);font-size:.7rem}.empty{border:1px dashed var(--border-strong);border-radius:var(--radius-md);background:#fff;padding:var(--space-7);text-align:center}.empty h2{font-size:.95rem}.empty p{color:var(--text-secondary);font-size:.76rem}@media(max-width:760px){.toolbar{align-items:stretch;flex-wrap:wrap}.search{min-width:100%}.result-count{display:none}.table-wrap{overflow:visible;border:0;background:transparent;box-shadow:none}thead{display:none}table,tbody,tr,td{display:block}tr{margin-bottom:.7rem;border:1px solid var(--border-default);border-radius:var(--radius-md);background:#fff;padding:.7rem}td{border:0;padding:.18rem}.pipeline-name small{white-space:normal}td:nth-child(3),td:nth-child(4),td:nth-child(5){display:none}.row-actions{justify-content:flex-start;margin-top:.4rem}}</style>
