import AxeBuilder from '@axe-core/playwright';
import { expect,test,type Page } from '@playwright/test';

async function signIn(page:Page,next='/home'){await page.goto(`/login?next=${encodeURIComponent(next)}`);await page.getByLabel('Username').fill('admin');await page.getByLabel('Password').fill('123');await page.getByRole('button',{name:'Sign in'}).click();await expect(page).toHaveURL(new RegExp(`${next.replaceAll('/','\\/')}$`))}
async function connectHandles(page:Page,from:string,to:string){const source=page.locator(`.svelte-flow__node[data-id="${from}"] .svelte-flow__handle.source`).first(),target=page.locator(`.svelte-flow__node[data-id="${to}"] .svelte-flow__handle.target`).first();const a=await source.boundingBox(),b=await target.boundingBox();if(!a||!b)throw new Error('Connection handles were not visible');await page.mouse.move(a.x+a.width/2,a.y+a.height/2);await page.mouse.down();await page.mouse.move(b.x+b.width/2,b.y+b.height/2,{steps:8});await page.mouse.up()}

test('supports Connection, authoring, version, Run, retry and schedule lifecycle',async({page})=>{
  test.setTimeout(90_000);await page.setViewportSize({width:1440,height:900});await signIn(page);
  await page.goto('/connections/new');await page.getByLabel('Connection name').fill(`Acceptance PostgreSQL ${Date.now()}`);await page.getByLabel('Host').fill('127.0.0.1');await page.getByLabel('Database',{exact:true}).fill('nexetl');await page.getByLabel('Username').fill('nexetl');await page.getByLabel(/Password/).fill('acceptance-placeholder');await page.getByRole('button',{name:'Create connection'}).click();await expect(page).toHaveURL(/\/connections\/[0-9a-f-]{36}$/);const connectionId=page.url().split('/').at(-1)!;await expect(page.getByText('The password is write-only.')).toBeVisible();
  await page.goto('/pipelines/new');await page.getByLabel('Name').fill(`Acceptance Pipeline ${Date.now()}`);await page.getByLabel('Description').fill('Browser lifecycle acceptance.');const createdResponse=page.waitForResponse(r=>r.request().method()==='POST'&&r.url().endsWith('/api/pipeline-definitions/'));await page.getByRole('button',{name:'Create and design'}).click();const createdPipeline=await (await createdResponse).json();const pipelineId=createdPipeline.id as string;await page.goto(`/pipelines/${pipelineId}/design`);await expect(page).toHaveURL(new RegExp(`/pipelines/${pipelineId}/design$`));
  await page.getByRole('button',{name:/Database Source/}).click();await page.getByRole('button',{name:/Select Columns/}).click();await page.getByRole('button',{name:/Database Target/}).click();const graphNodes=page.locator('.svelte-flow__node');await expect(graphNodes).toHaveCount(3);const sourceId=await graphNodes.nth(0).getAttribute('data-id'),selectId=await graphNodes.nth(1).getAttribute('data-id'),targetId=await graphNodes.nth(2).getAttribute('data-id');if(!sourceId||!selectId||!targetId)throw new Error('Node IDs missing');
  await graphNodes.nth(0).click();await page.getByLabel('Connection').selectOption(connectionId);await page.getByLabel('Schema').fill('public');await page.getByLabel('Table or view').fill('acceptance_source');
  await graphNodes.nth(1).click();const selected=page.getByLabel('Selected columns in order (JSON)');await selected.fill('["id"]');await selected.blur();
  await graphNodes.nth(2).click();await page.getByLabel('Connection').selectOption(connectionId);await page.getByLabel('Schema').fill('public');await page.getByLabel('Target table').fill('acceptance_target');
  await connectHandles(page,sourceId,selectId);await connectHandles(page,selectId,targetId);await expect(page.locator('.svelte-flow__edge')).toHaveCount(2);await page.getByRole('button',{name:'Save'}).click();await expect(page.getByText('Saved',{exact:true})).toBeVisible();await page.getByRole('button',{name:'Validate',exact:true}).click();await expect(page.getByText('Pipeline structure valid')).toBeVisible();
  expect((await new AxeBuilder({page}).analyze()).violations.filter(v=>v.impact==='critical'||v.impact==='serious')).toEqual([]);
  await page.getByRole('button',{name:'Run pipeline'}).click();await expect(page).toHaveURL(new RegExp(`/pipelines/${pipelineId}/runs/[0-9a-f-]{36}$`));await expect(page.getByText('QUEUED',{exact:true}).first()).toBeVisible();await page.getByRole('button',{name:'Cancel'}).click();await expect(page.getByText('CANCELLED',{exact:true}).first()).toBeVisible();await page.getByRole('button',{name:'Retry run'}).click();await expect(page.getByText('QUEUED',{exact:true}).first()).toBeVisible();
  await page.goto(`/pipelines/${pipelineId}/schedules`);await page.getByRole('button',{name:'Create schedule'}).click();await expect(page.getByText('Daily run')).toBeVisible();
});

test('uses deliberate responsive layouts and accessible navigation',async({browser})=>{for(const viewport of [{width:1024,height:768},{width:768,height:900},{width:375,height:812}]){const context=await browser.newContext({baseURL:'http://localhost:5173',viewport});const page=await context.newPage();await signIn(page,'/pipelines');await expect(page.getByRole('heading',{name:'Pipelines'})).toBeVisible();expect(await page.evaluate(()=>document.documentElement.scrollWidth)).toBe(viewport.width);expect((await new AxeBuilder({page}).analyze()).violations.filter(v=>v.impact==='critical')).toEqual([]);await context.close()}});
