import AxeBuilder from '@axe-core/playwright';
import { expect, test } from '@playwright/test';

test('uses the real Django session for login, Pipeline registration, inspection, and logout', async ({ page }) => {
  await page.goto('/');
  await expect(page).toHaveURL(/\/login\?next=%2Fhome$/);
  await expect(page.getByRole('heading', { name: 'Welcome to NEXETL' })).toBeVisible();
  await expect(page.getByRole('navigation')).toHaveCount(0);
  expect((await new AxeBuilder({ page }).analyze()).violations.filter((violation) => violation.impact === 'critical')).toEqual([]);

  await page.getByLabel('Username').fill('admin');
  await page.getByLabel('Password').fill('123');
  await page.getByRole('button', { name: 'Sign in' }).click();
  await expect(page).toHaveURL(/\/home$/);
  await expect(page.getByRole('navigation', { name: 'Primary navigation' })).toBeVisible();
  await page.getByRole('button', { name: 'Collapse navigation' }).click();
  await expect(page.getByRole('button', { name: 'Expand navigation' })).toBeVisible();
  await expect(page.getByRole('navigation', { name: 'Primary navigation' }).getByText('Pipelines', { exact: true })).not.toBeVisible();
  await page.reload();
  await expect(page.getByRole('button', { name: 'Expand navigation' })).toBeVisible();
  await page.getByRole('button', { name: 'Expand navigation' }).click();
  await expect(page.getByRole('navigation', { name: 'Primary navigation' }).getByText('Pipelines', { exact: true })).toBeVisible();
  expect((await new AxeBuilder({ page }).analyze()).violations.filter((violation) => violation.impact === 'critical')).toEqual([]);

  await page.goto('/pipelines/new');
  await expect(page.getByRole('main')).toContainText('Create Pipeline');
  await page.getByLabel('Name').fill('Customer Warehouse Load');
  await page.getByLabel('Description').fill('Curates customer orders for the warehouse.');
  await page.getByRole('button', { name: 'Create and design' }).click();
  await expect(page).toHaveURL(/\/pipelines\/[0-9a-f-]{36}\/design$/);
  const id = page.url().split('/').at(-2)!;
  await expect(page.getByRole('heading', { name: 'Customer Warehouse Load' })).toBeVisible();
  await page.getByRole('button', { name: /Source/ }).click();
  await page.getByRole('button', { name: /Transform/ }).click();
  await page.getByRole('button', { name: /Target/ }).click();
  const canvas = page.getByLabel('Pipeline design canvas');
  await expect(canvas.getByRole('button', { name: /node$/ })).toHaveCount(3);
  await canvas.getByRole('button', { name: /source node$/ }).click();
  await page.getByLabel('Label').fill('PostgreSQL Orders');
  await canvas.getByRole('button', { name: /transform node$/ }).click();
  await page.getByLabel('Label').fill('Clean Orders');
  await canvas.getByRole('button', { name: /target node$/ }).click();
  await page.getByLabel('Label').fill('Warehouse');
  await page.getByText('Connection', { exact: true }).click();
  await page.locator('details select').nth(0).selectOption({ index: 1 });
  await page.locator('details select').nth(1).selectOption({ index: 1 });
  await page.getByRole('button', { name: 'Connect nodes' }).click();
  await page.locator('details select').nth(0).selectOption({ index: 2 });
  await page.locator('details select').nth(1).selectOption({ index: 2 });
  await page.getByRole('button', { name: 'Connect nodes' }).click();
  const transformNode = canvas.getByRole('button', { name: /Clean Orders, transform node$/ });
  const beforeDrag = await transformNode.boundingBox();
  if (!beforeDrag) throw new Error('Transform node was not visible for drag verification');
  await page.mouse.move(beforeDrag.x + 60, beforeDrag.y + 30);
  await page.mouse.down();
  await page.mouse.move(beforeDrag.x + 120, beforeDrag.y + 80, { steps: 5 });
  await page.mouse.up();
  const draggedStyle = await transformNode.getAttribute('style');
  expect(draggedStyle).not.toBeNull();
  await page.getByRole('button', { name: 'Save' }).click();
  await expect(page.getByText('Saved', { exact: true })).toBeVisible();
  await page.reload();
  await expect(page.getByLabel('Pipeline design canvas').getByRole('button', { name: /node$/ })).toHaveCount(3);
  await expect(page.getByRole('button', { name: /Clean Orders, transform node$/ })).toHaveAttribute('style', draggedStyle!);
  await page.getByRole('button', { name: 'Validate' }).click();
  await expect(page.getByText('Pipeline structure valid')).toBeVisible();
  expect((await new AxeBuilder({ page }).analyze()).violations.filter((violation) => violation.impact === 'critical')).toEqual([]);

  await page.goto(`/pipelines/${id}`);
  await page.getByRole('button', { name: 'Archive' }).click();
  await page.getByRole('dialog').getByRole('button', { name: 'Archive' }).click();
  await expect(page.getByText('Archived Pipeline Definitions are read only.')).toBeVisible();
  await page.goto(`/pipelines/${id}/design`);
  await expect(page.getByText('Read only', { exact: true })).toBeVisible();
  await expect(page.getByRole('button', { name: /Source/ })).toBeDisabled();
  await expect(page.getByRole('button', { name: 'Save' })).toHaveCount(0);

  await page.getByRole('button', { name: 'Sign out' }).click();
  await expect(page).toHaveURL(/\/login$/);
  await page.goto(`/pipelines/${id}`);
  await expect(page).toHaveURL(/\/login\?next=/);
});
